'use strict';

/**
 * Static publisher for travel landing pages hosted on a tenant's own site.
 *
 * The configured remote path is the directory already owned by the transfer
 * account (for example `main-forms`). A trip landing page is written directly
 * to `<configured-root>/<page id>/index.html`. The public URL remains
 * `/trips/<page id>`; the customer's web server must map that URL to the
 * corresponding static folder.
 */

const path = require('path');
const { Readable } = require('node:stream');
const { renderPage } = require('./landingPageRenderer');

const DEFAULT_REMOTE_PATH = '/';
const DEFAULT_CRM_BASE_URL = 'https://globuscrm.globussoft.com';
const SUPPORTED_PROTOCOLS = ['ftp', 'ftps', 'sftp'];
const DEFAULT_PORTS = { ftp: 21, ftps: 21, sftp: 22 };

function normalizeProtocol(value = 'sftp') {
  const protocol = String(value || 'sftp').trim().toLowerCase();
  if (!SUPPORTED_PROTOCOLS.includes(protocol)) {
    throw new Error('Transfer protocol must be FTP, FTPS, or SFTP');
  }
  return protocol;
}

function getDefaultPort(protocol = 'sftp') {
  return DEFAULT_PORTS[normalizeProtocol(protocol)];
}

function normalizeCrmBaseUrl(value = process.env.PUBLIC_CRM_URL || process.env.FRONTEND_URL || DEFAULT_CRM_BASE_URL) {
  try {
    const parsed = new URL(String(value).trim());
    if (!['http:', 'https:'].includes(parsed.protocol)) return DEFAULT_CRM_BASE_URL;
    return `${parsed.origin}${parsed.pathname.replace(/\/+$/, '')}`;
  } catch (_err) {
    return DEFAULT_CRM_BASE_URL;
  }
}

function normalizeRemotePath(value = DEFAULT_REMOTE_PATH) {
  const raw = String(value || DEFAULT_REMOTE_PATH).trim().replace(/\\/g, '/');
  const rawSegments = raw.split('/').filter(Boolean);
  if (rawSegments.includes('..')) {
    throw new Error('Remote website path must be a safe directory path');
  }
  const normalized = path.posix.normalize(raw.startsWith('/') ? raw : `/${raw}`);
  if (normalized.includes('/../') || normalized === '..' || normalized.startsWith('../')) {
    throw new Error('Remote website path must be a safe directory path');
  }
  const withoutTrailingSlash = normalized === '/' ? '/' : (normalized.replace(/\/+$/, '') || DEFAULT_REMOTE_PATH);
  // The first version of this feature asked for a `trips` directory. Treat
  // that exact trailing segment as a legacy setting so an existing tenant
  // automatically moves to the new account-root layout on its next publish.
  if (withoutTrailingSlash !== '/' && path.posix.basename(withoutTrailingSlash) === 'trips') {
    return path.posix.dirname(withoutTrailingSlash) || '/';
  }
  return withoutTrailingSlash;
}

function getRemoteTripDirectory(remotePath, pageId) {
  const id = Number(pageId);
  if (!Number.isInteger(id) || id <= 0) throw new Error('Landing page id must be a positive integer');
  return path.posix.join(normalizeRemotePath(remotePath), String(id));
}

function getRemoteTripFile(remotePath, pageId) {
  return path.posix.join(getRemoteTripDirectory(remotePath, pageId), 'index.html');
}

function getPublicTripUrl(websiteUrl, pageId) {
  const id = Number(pageId);
  if (!Number.isInteger(id) || id <= 0) throw new Error('Landing page id must be a positive integer');
  return new URL(`/trips/${id}`, `${String(websiteUrl).replace(/\/+$/, '')}/`).toString();
}

// Public HTML is generated by the CRM, but it is served from the client's
// origin. Convert all CRM-relative API paths to absolute CRM paths so form
// submissions, payment calls, tracking pixels, and the Wanderlux runtime keep
// working after the file is copied to the client's website.
function absolutizeCrmUrls(html, crmBaseUrl) {
  const base = normalizeCrmBaseUrl(crmBaseUrl);
  return String(html || '').replace(/(["'(`=])\/(api|p)\//g, `$1${base}/$2/`);
}

function addAvailabilityGate(html, { pageId, crmBaseUrl }) {
  const base = normalizeCrmBaseUrl(crmBaseUrl);
  const statusUrl = `${base}/api/landing-pages/public/status/${encodeURIComponent(String(pageId))}`;
  const gate = `<style id="crm-trip-availability-style">body{visibility:hidden}</style>
<script>
(function(){
  var unavailable=function(){
    document.body.innerHTML='<main style="min-height:100vh;display:grid;place-items:center;padding:2rem;font-family:system-ui,sans-serif;text-align:center"><div><h1>This trip page is unavailable</h1><p>Please contact the travel organiser for an updated link.</p></div></main>';
    document.body.style.visibility='visible';
  };
  fetch(${JSON.stringify(statusUrl)}, {headers:{Accept:'application/json'}, cache:'no-store'})
    .then(function(response){if(!response.ok)throw new Error('unpublished');document.body.style.visibility='visible';})
    .catch(unavailable);
})();
</script>`;
  if (String(html).includes('</head>')) {
    return String(html).replace('</head>', `${gate}</head>`);
  }
  return `${gate}${html}`;
}

function renderHostedLandingPage(page, { crmBaseUrl, availabilityGate = true, tmcParentRegistrationUrl } = {}) {
  const html = renderPage(page, { preview: false, tmcParentRegistrationUrl });
  const absoluteHtml = absolutizeCrmUrls(html, crmBaseUrl);
  return availabilityGate
    ? addAvailabilityGate(absoluteHtml, { pageId: page.id, crmBaseUrl })
    : absoluteHtml;
}

function createSftpClient() {
  // Lazy loading keeps route/unit tests usable in environments that do not
  // install the optional network clients until hosting is enabled.
  const SftpClient = require('ssh2-sftp-client');
  return new SftpClient();
}

function createFtpClient() {
  const { Client } = require('basic-ftp');
  return new Client();
}

function connectionOptions(config) {
  const options = {
    host: String(config.host || '').trim(),
    port: Number(config.port || getDefaultPort('sftp')),
    username: String(config.username || '').trim(),
    readyTimeout: 15000,
  };
  if (config.password) options.password = String(config.password);
  if (config.privateKey) options.privateKey = String(config.privateKey);
  if (config.passphrase) options.passphrase = String(config.passphrase);
  return options;
}

function ftpConnectionOptions(config) {
  const protocol = normalizeProtocol(config.protocol);
  const port = Number(config.port || getDefaultPort(protocol));
  return {
    host: String(config.host || '').trim(),
    port,
    user: String(config.username || '').trim(),
    password: String(config.password || ''),
    secure: protocol === 'ftps' ? (port === 990 ? 'implicit' : true) : false,
  };
}

function validateTransportConfig(config) {
  const protocol = normalizeProtocol(config?.protocol);
  if (!config || !String(config.host || '').trim() || !String(config.username || '').trim()) {
    throw new Error(`Complete ${protocol.toUpperCase()} connection details are required`);
  }
  if (protocol === 'sftp' && !config.password && !config.privateKey) {
    throw new Error('SFTP password or private key is required');
  }
  if (protocol !== 'sftp' && !config.password) {
    throw new Error(`${protocol.toUpperCase()} password is required`);
  }
  const port = Number(config.port || getDefaultPort(protocol));
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error('Transfer port must be between 1 and 65535');
  }
}

async function withRemoteClient(config, fn, {
  clientFactory = createSftpClient,
  ftpClientFactory = createFtpClient,
} = {}) {
  const protocol = normalizeProtocol(config?.protocol);
  validateTransportConfig(config);
  const client = protocol === 'sftp' ? clientFactory() : ftpClientFactory();
  if (protocol === 'sftp') {
    try {
      await client.connect(connectionOptions(config));
      return await fn(client, protocol);
    } finally {
      await client.end().catch(() => {});
    }
  }

  try {
    await client.access(ftpConnectionOptions(config));
    return await fn(client, protocol);
  } finally {
    client.close();
  }
}

async function withSftp(config, fn, options = {}) {
  return withRemoteClient({ ...config, protocol: 'sftp' }, fn, options);
}

async function ensureRemoteDirectory(client, protocol, directory) {
  if (protocol === 'sftp') return client.mkdir(directory, false);
  return client.ensureDir(directory);
}

function isRemoteDirectoryEntry(entry) {
  return entry && (entry.type === 'd' || entry.type === 'directory' || entry.type === 2 || entry.type === '2');
}

async function ensureRemoteTripDirectory(client, protocol, remotePath, directory) {
  const tripFolderName = path.posix.basename(directory);
  const usesAccountRoot = protocol === 'ftp' || protocol === 'ftps';
  // FTP/FTPS accounts can be jailed directly to main-forms. In that case
  // '/' is already the supplied directory, so never pass the server's
  // /home/... path to the FTP server.
  const entries = usesAccountRoot
    ? await client.list()
    : await client.list(normalizeRemotePath(remotePath));
  const existingEntry = entries.find((entry) => entry.name === tripFolderName);
  if (existingEntry && !isRemoteDirectoryEntry(existingEntry)) {
    throw new Error(`Remote trip path is occupied by a file: ${directory}`);
  }
  if (usesAccountRoot) {
    // This is relative to the logged-in account root: only <trip-id> is
    // created. basic-ftp enters that new/existing child for the upload.
    await client.ensureDir(directory);
    return;
  }
  if (!existingEntry) await ensureRemoteDirectory(client, protocol, directory);
}

async function putRemoteBuffer(client, protocol, buffer, remoteFile) {
  if (protocol === 'sftp') return client.put(buffer, remoteFile);
  // basic-ftp is already in the verified numeric trip folder.
  return client.uploadFrom(Readable.from([buffer]), path.posix.basename(remoteFile));
}

async function publishLandingPage({ page, sftp, remotePath, websiteUrl, crmBaseUrl, tmcParentRegistrationUrl, clientFactory, ftpClientFactory } = {}) {
  if (!page || !page.id) throw new Error('Landing page is required');
  const html = renderHostedLandingPage(page, { crmBaseUrl, tmcParentRegistrationUrl });
  await withRemoteClient({ ...sftp, remotePath }, async (client, protocol) => {
    const usesAccountRoot = protocol === 'ftp' || protocol === 'ftps';
    const directory = usesAccountRoot
      ? String(page.id)
      : getRemoteTripDirectory(remotePath, page.id);
    const remoteFile = usesAccountRoot
      ? path.posix.join(String(page.id), 'index.html')
      : getRemoteTripFile(remotePath, page.id);
    await ensureRemoteTripDirectory(client, protocol, remotePath, directory);
    await putRemoteBuffer(client, protocol, Buffer.from(html, 'utf8'), remoteFile);
  }, { clientFactory, ftpClientFactory });
  return {
    remoteFile: normalizeProtocol(sftp?.protocol) === 'ftp' || normalizeProtocol(sftp?.protocol) === 'ftps'
      ? path.posix.join(String(page.id), 'index.html')
      : getRemoteTripFile(remotePath, page.id),
    publicUrl: getPublicTripUrl(websiteUrl, page.id),
  };
}

async function removeRemoteDirectory(client, directory, protocol = 'sftp') {
  try {
    if (protocol === 'sftp') await client.rmdir(directory, true);
    else await client.removeDir(directory);
  } catch (err) {
    // Deletion is idempotent: a manually removed folder should not prevent
    // the corresponding CRM page from being deleted. Permission/auth errors
    // still propagate so the CRM row is not removed while the remote copy
    // remains inaccessible.
    if (!/not found|no such file|does not exist|cannot find/i.test(String(err?.message || ''))) throw err;
  }
}

async function removeLandingPage({ pageId, sftp, remotePath, clientFactory, ftpClientFactory } = {}) {
  await withRemoteClient({ ...sftp, remotePath }, async (client, protocol) => {
    const usesAccountRoot = protocol === 'ftp' || protocol === 'ftps';
    const directory = usesAccountRoot ? String(pageId) : getRemoteTripDirectory(remotePath, pageId);
    await removeRemoteDirectory(client, directory, protocol);
  }, { clientFactory, ftpClientFactory });
  const protocol = normalizeProtocol(sftp?.protocol);
  return {
    remoteFile: protocol === 'ftp' || protocol === 'ftps'
      ? path.posix.join(String(pageId), 'index.html')
      : getRemoteTripFile(remotePath, pageId),
  };
}

module.exports = {
  DEFAULT_REMOTE_PATH,
  DEFAULT_CRM_BASE_URL,
  SUPPORTED_PROTOCOLS,
  normalizeProtocol,
  getDefaultPort,
  normalizeCrmBaseUrl,
  normalizeRemotePath,
  getRemoteTripDirectory,
  getRemoteTripFile,
  getPublicTripUrl,
  absolutizeCrmUrls,
  addAvailabilityGate,
  renderHostedLandingPage,
  connectionOptions,
  ftpConnectionOptions,
  validateTransportConfig,
  withRemoteClient,
  withSftp,
  ensureRemoteDirectory,
  putRemoteBuffer,
  publishLandingPage,
  removeLandingPage,
  removeRemoteDirectory,
};
