export const ledgerTypes = [
  "Sales",
  "Purchase",
  "GST",
  "TCS",
  "GST/TCS",
  "Bank",
  "Cash",
  "Expense",
  "Trip-wise",
  "Custom",
];

export const ledgerGroups = [
  "Sales Accounts",
  "Purchase Accounts",
  "Duties & Taxes",
  "Sundry Debtors",
  "Sundry Creditors",
  "Bank Accounts",
  "Cash-in-hand",
  "Indirect Expenses",
  "Indirect Incomes",
  "Current Assets",
  "Current Liabilities",
];

export const ledgerNatures = [
  "Sales",
  "Purchase",
  "Duties & Taxes",
  "Sundry Debtor",
  "Sundry Creditor",
  "Cash",
  "Bank",
  "Indirect Expense",
  "Indirect Income",
];

export const gstApplicabilityOptions = [
  { value: "applicable", label: "Applicable" },
  { value: "not-applicable", label: "Not applicable" },
  { value: "exempt", label: "Exempt" },
];

export const systemLedgers = [
  {
    id: "sales",
    name: "Sales Ledger",
    type: "Sales",
    group: "Sales Accounts",
    nature: "Sales",
    gstApplicability: "applicable",
    billWise: false,
    openingBalance: 0,
  },
  {
    id: "purchase",
    name: "Purchase Ledger",
    type: "Purchase",
    group: "Purchase Accounts",
    nature: "Purchase",
    gstApplicability: "applicable",
    billWise: true,
    openingBalance: 0,
  },
  {
    id: "outputGst",
    name: "GST/TCS Ledger",
    type: "GST/TCS",
    group: "Duties & Taxes",
    nature: "Duties & Taxes",
    gstApplicability: "applicable",
    billWise: false,
    openingBalance: 0,
  },
  {
    id: "bank",
    name: "Bank Ledger",
    type: "Bank",
    group: "Bank Accounts",
    nature: "Bank",
    gstApplicability: "not-applicable",
    billWise: false,
    openingBalance: 0,
  },
  {
    id: "cash",
    name: "Cash Ledger",
    type: "Cash",
    group: "Cash-in-hand",
    nature: "Cash",
    gstApplicability: "not-applicable",
    billWise: false,
    openingBalance: 0,
  },
  {
    id: "officeExpenses",
    name: "Office Expenses Ledger",
    type: "Expense",
    group: "Indirect Expenses",
    nature: "Indirect Expense",
    gstApplicability: "applicable",
    billWise: false,
    openingBalance: 0,
  },
  {
    id: "tripwise",
    name: "Trip-wise Ledger",
    type: "Trip-wise",
    group: "Current Assets",
    nature: "Indirect Income",
    gstApplicability: "not-applicable",
    billWise: false,
    openingBalance: 0,
  },
];

export const emptyLedgerForm = {
  id: "",
  name: "",
  type: "Sales",
  group: "Sales Accounts",
  nature: "Sales",
  gstApplicability: "applicable",
  billWise: false,
  openingBalance: "",
  openingBalanceType: "DEBIT",
  tdsApplicable: false,
  effectiveFrom: "",
  subBrand: "all",
  custom: true,
};
