import { useEffect, useState } from "react";
import TallySectionNav, { TallyWriteGate } from "./TallySectionNav";
import { fetchApi } from "../../../utils/api";

export default function TallyServiceMappingPage() {
  const [rows, setRows] = useState([]); const [ledgers, setLedgers] = useState([]); const [services, setServices] = useState([]); const [selected, setSelected] = useState({}); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async () => { setError(""); try { const [mappingData, masterData, sourceData] = await Promise.all([fetchApi("/api/travel/tally/mappings"), fetchApi("/api/travel/tally/accounting-masters"), fetchApi("/api/travel/tally/mapping-sources")]); setRows(mappingData?.mappings || []); setLedgers(masterData?.ledgers || []); setServices(sourceData?.services || []); } catch (loadError) { setError(loadError.message || "Could not load service mappings."); } };
  useEffect(() => { load(); }, []);
  const find = (service, type) => rows.find((row) => row.sourceType === "SERVICE" && row.sourceKey === `SERVICE:${service.toLowerCase()}` && row.transactionType === type);
  const save = async (service, type) => { const id = Number(selected[`${service}-${type}`] || find(service, type)?.tallyLedgerId); if (!id) return; setError(""); setMessage(""); try { await fetchApi("/api/travel/tally/mappings", { method: "POST", body: JSON.stringify({ sourceType: "SERVICE", sourceKey: `SERVICE:${service.toLowerCase()}`, transactionType: type, tallyLedgerId: id }) }); setMessage(`${service} ${type.toLowerCase()} mapping saved.`); await load(); } catch (saveError) { setError(saveError.message || "Could not save service mapping."); } };
  return <main style={{ padding: 24, maxWidth: 1180, margin: "0 auto" }}><TallySectionNav /><h1>Service Mapping</h1><p style={{ color: "var(--text-secondary)" }}>Map each service found in your itineraries. The same user-created ledger can be reused for multiple services.</p>{message && <p style={{ color: "#2f855a" }}>{message}</p>}{error && <p role="alert" style={{ color: "#c53030" }}>{error}</p>}{services.length === 0 ? <p style={{ color: "var(--text-secondary)" }}>No itinerary services found yet.</p> : <table><thead><tr><th>Service</th><th>Sales ledger</th><th>Purchase ledger</th><th>Actions</th></tr></thead><tbody>{services.map((service) => <tr key={service}><td>{service}</td>{["SALES", "PURCHASE"].map((type) => { const row = find(service, type); const key = `${service}-${type}`; return <td key={type}><select value={selected[key] || row?.tallyLedgerId || ""} onChange={(e) => setSelected({ ...selected, [key]: e.target.value })}><option value="">Select ledger</option>{ledgers.filter((ledger) => ledger.ledgerCategory === type || ledger.ledgerCategory === "CUSTOM").map((ledger) => <option key={ledger.id} value={ledger.id}>{ledger.ledgerName}</option>)}</select></td>; })}<td><TallyWriteGate><button type="button" onClick={() => save(service, "SALES")}>Save Sales</button><button type="button" onClick={() => save(service, "PURCHASE")} style={{ marginLeft: 6 }}>Save Purchase</button></TallyWriteGate></td></tr>)}</tbody></table>}</main>;
}
