import { useEffect, useState } from "react";
import TallySectionNav, { TallyWriteGate } from "./TallySectionNav";
import { fetchApi } from "../../../utils/api";

export default function TallyCostCentresPage() {
  const [rows, setRows] = useState([]); const [trips, setTrips] = useState([]); const [itineraryId, setItineraryId] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async () => { const data = await fetchApi("/api/travel/tally/cost-centres"); setRows(data?.costCentres || []); };
  useEffect(() => { Promise.all([load(), fetchApi("/api/travel/itineraries?fields=summary&limit=500").then((data) => setTrips(data?.itineraries || []))]).catch((loadError) => setError(loadError.message || "Could not load cost centre data.")); }, []);
  const save = async (event) => { event.preventDefault(); setError(""); setMessage(""); try { await fetchApi("/api/travel/tally/cost-centres", { method: "POST", body: JSON.stringify({ itineraryId }), headers: { "Content-Type": "application/json" } }); setItineraryId(""); setMessage("Cost centre saved."); await load(); } catch (saveError) { setError(saveError.message || "Could not save cost centre."); } };
  const createMissing = async () => { setError(""); setMessage(""); try { const existing = new Set(rows.map((row) => String(row.itineraryId))); const missing = trips.filter((trip) => !existing.has(String(trip.id))); await Promise.all(missing.map((trip) => fetchApi("/api/travel/tally/cost-centres", { method: "POST", body: JSON.stringify({ itineraryId: trip.id }), headers: { "Content-Type": "application/json" } }))); setMessage(missing.length ? `${missing.length} cost centre(s) prepared.` : "All trips already have cost centres."); await load(); } catch (saveError) { setError(saveError.message || "Could not prepare missing cost centres."); } };
  return <main style={{ padding: 24, maxWidth: 1180, margin: "0 auto" }}><TallySectionNav /><h1>Trip Cost Centres</h1><p style={{ color: "var(--text-secondary)" }}>A local cost centre is automatically created for new trips and can be prepared for future Tally sync.</p><TallyWriteGate><form onSubmit={save} style={formStyle}><label>Trip / Itinerary<select value={itineraryId} onChange={(e) => setItineraryId(e.target.value)} required><option value="">Select trip</option>{trips.map((trip) => <option key={trip.id} value={trip.id}>TRIP-{trip.id} - {trip.destination || "Trip"}</option>)}</select></label><button type="submit">Create or Refresh</button><button type="button" onClick={createMissing}>Prepare Missing</button></form></TallyWriteGate>{message && <p style={{ color: "#2f855a" }}>{message}</p>}{error && <p role="alert" style={{ color: "#c53030" }}>{error}</p>}<table><thead><tr><th>Code</th><th>Name</th><th>Trip</th><th>Status</th><th>Sync status</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td>{row.code}</td><td>{row.name}</td><td>{row.itinerary?.destination || row.itineraryId}</td><td>{row.status}</td><td>{row.syncStatus}</td></tr>) : <tr><td colSpan="5">No trip cost centres yet.</td></tr>}</tbody></table></main>;
}

const formStyle = { display: "grid", gridTemplateColumns: "minmax(220px, 1fr) auto auto", gap: 14, alignItems: "end", margin: "18px 0 24px", padding: 16, border: "1px solid var(--border-color, rgba(148,163,184,.2))", borderRadius: 12, background: "var(--surface-color)" };
