import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import TallySectionNav, { TallyWriteGate } from "./TallySectionNav";
import { fetchApi } from "../../../utils/api";

export default function TallyPartyMappingPage() {
  const navigate = useNavigate();
  const [rows, setRows] = useState([]); const [ledgers, setLedgers] = useState([]); const [selected, setSelected] = useState({}); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async () => { setError(""); try { const [mappingData, masterData] = await Promise.all([fetchApi("/api/travel/tally/mappings"), fetchApi("/api/travel/tally/accounting-masters")]); setRows((mappingData?.mappings || []).filter((row) => ["CUSTOMER", "SUPPLIER"].includes(row.sourceType))); setLedgers(masterData?.ledgers || []); } catch (loadError) { setError(loadError.message || "Could not load party mappings."); } };
  useEffect(() => { load(); }, []);
  const save = async (row) => { const id = Number(selected[row.id] || row.tallyLedgerId); if (!id) return; setError(""); setMessage(""); try { await fetchApi(`/api/travel/tally/mappings/${row.id}`, { method: "PUT", body: JSON.stringify({ tallyLedgerId: id }) }); setMessage(`${row.sourceKey} mapping saved.`); await load(); } catch (saveError) { setError(saveError.message || "Could not save party mapping."); } };
  return <main className="tally-mapping-page tally-party-mapping-page"><TallySectionNav /><div className="tally-mapping-header"><div><span className="tally-mapping-eyebrow">Finance / Tally</span><h1>Party Mapping</h1><p>Map website customers and suppliers to their local Tally ledgers.</p></div><button className="tally-mapping-queue-button" type="button" onClick={() => navigate("/travel/tally/sync-queue")}>Sync Queue <span aria-hidden="true">→</span></button></div>{message && <p className="tally-mapping-message">{message}</p>}{error && <p className="tally-mapping-error" role="alert">{error}</p>}<div className="tally-mapping-card"><div className="tally-mapping-card-heading"><div><h2>Party ledger assignments</h2><p>Connect customers and suppliers to their Tally ledgers.</p></div><span>{rows.length} {rows.length === 1 ? "party" : "parties"}</span></div><div className="tally-mapping-table-wrap"><table><thead><tr><th>Party</th><th>Type</th><th>Transaction</th><th>Tally ledger</th><th>Action</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td><strong>{row.sourceKey}</strong></td><td><span className="tally-mapping-type">{row.sourceType}</span></td><td>{row.transactionType}</td><td><select value={selected[row.id] || row.tallyLedgerId} onChange={(e) => setSelected({ ...selected, [row.id]: e.target.value })}>{ledgers.map((ledger) => <option key={ledger.id} value={ledger.id}>{ledger.ledgerName}</option>)}</select></td><td><TallyWriteGate><button className="tally-mapping-save" type="button" onClick={() => save(row)}>Save</button></TallyWriteGate></td></tr>) : <tr><td className="tally-mapping-empty-cell" colSpan="5">Party ledgers will appear automatically when customers or suppliers are created.</td></tr>}</tbody></table></div></div></main>;
}
