import { useEffect, useState } from "react";
import TallySectionNav, { TallyWriteGate } from "./TallySectionNav";
import { fetchApi } from "../../../utils/api";

export default function TallyCostCentresPage() {
  const [rows, setRows] = useState([]); const [sources, setSources] = useState([]); const [selectedSource, setSelectedSource] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async () => { const data = await fetchApi("/api/travel/tally/cost-centres"); setRows(data?.costCentres || []); setSources(data?.sources || []); };
  useEffect(() => { load().catch((loadError) => setError(loadError.message || "Could not load cost centre data.")); }, []);
  const save = async (event) => { event.preventDefault(); setError(""); setMessage(""); try { const [sourceType, sourceId] = selectedSource.split(":"); await fetchApi("/api/travel/tally/cost-centres", { method: "POST", body: JSON.stringify({ sourceType, sourceId: Number(sourceId) }), headers: { "Content-Type": "application/json" } }); setSelectedSource(""); setMessage("Cost centre saved."); await load(); } catch (saveError) { setError(saveError.message || "Could not save cost centre."); } };
  const createMissing = async () => { setError(""); setMessage(""); try { const result = await fetchApi("/api/travel/tally/cost-centres/prepare-missing", { method: "POST" }); setMessage(result?.created ? `${result.created} cost centre(s) prepared.` : "All itineraries, TMC trips, and quote-only trips already have cost centres."); await load(); } catch (saveError) { setError(saveError.message || "Could not prepare missing cost centres."); } };
  const tripLabel = (row) => row.itinerary?.destination || (row.tmcTrip ? `${row.tmcTrip.tripCode} - ${row.tmcTrip.destination}` : null) || (row.quote ? `Quote for ${row.quote.contact?.name || `#${row.quote.id}`}` : null) || `${row.sourceType} #${row.sourceId}`;
  return <main className="tally-cost-centres-page"><TallySectionNav /><div className="tally-cost-centres-eyebrow">FINANCE / TALLY</div><h1>Trip Cost Centres</h1><p className="tally-cost-centres-description">Cost centres are tracked for itineraries, TMC trips, and quote-only trips, then exported to Tally with their transactions.</p><TallyWriteGate><form onSubmit={save} className="tally-cost-centres-form"><label><span>Trip / Quote</span><select value={selectedSource} onChange={(e) => setSelectedSource(e.target.value)} required><option value="">Select trip or quote</option>{sources.map((source) => <option key={`${source.sourceType}:${source.sourceId}`} value={`${source.sourceType}:${source.sourceId}`}>{source.code} - {source.label}</option>)}</select></label><button type="submit">Create or Refresh</button><button type="button" onClick={createMissing}>Prepare Missing</button></form></TallyWriteGate>{message && <p className="tally-cost-centres-message">{message}</p>}{error && <p role="alert" className="tally-cost-centres-error">{error}</p>}<div className="tally-cost-centres-table-wrap"><table className="tally-cost-centres-table"><thead><tr><th>Code</th><th>Name</th><th>Trip / Quote</th><th>Status</th><th>Sync status</th><th>Action</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td>{row.code}</td><td>{row.name}</td><td>{tripLabel(row)}</td><td><span className="tally-cost-centres-badge tally-cost-centres-badge--active">{row.status}</span></td><td><span className="tally-cost-centres-badge tally-cost-centres-badge--sync">{row.syncStatus}</span></td><td>Built-in</td></tr>) : <tr><td colSpan="6">No trip cost centres yet.</td></tr>}</tbody></table></div></main>;
}
