import { useCallback, useEffect, useRef, useState } from "react";
import TallySectionNav, { TallyWriteGate } from "./TallySectionNav";
import { fetchApi } from "../../../utils/api";

export default function TallyCostCentresPage() {
  const [rows, setRows] = useState([]); const [sources, setSources] = useState([]); const [selectedSource, setSelectedSource] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const [page, setPage] = useState(1); const [hasMoreRows, setHasMoreRows] = useState(false); const [sourcePage, setSourcePage] = useState(1); const [hasMoreSources, setHasMoreSources] = useState(false); const [preparing, setPreparing] = useState(false); const [loadingSources, setLoadingSources] = useState(false);
  const loadRequestId = useRef(0);
  const load = useCallback(async ({ nextPage, nextSourcePage, appendSources = false }) => {
    const requestId = ++loadRequestId.current;
    const params = new URLSearchParams({ page: String(nextPage), limit: "50", sourcePage: String(nextSourcePage), sourceLimit: "100" });
    const data = await fetchApi(`/api/travel/tally/cost-centres?${params}`);
    if (requestId !== loadRequestId.current) return false;
    setRows(data?.costCentres || []);
    setHasMoreRows(Boolean(data?.pagination?.hasMore));
    setSources((current) => {
      const combined = appendSources ? [...current, ...(data?.sources || [])] : (data?.sources || []);
      return [...new Map(combined.map((source) => [`${source.sourceType}:${source.sourceId}`, source])).values()];
    });
    setHasMoreSources(Boolean(data?.sourcePagination?.hasMore));
    return true;
  }, []);
  useEffect(() => { load({ nextPage: 1, nextSourcePage: 1 }).catch((loadError) => setError(loadError.message || "Could not load cost centre data.")); }, [load]);
  const changePage = async (nextPage) => { setError(""); try { if (await load({ nextPage, nextSourcePage: 1 })) { setPage(nextPage); setSourcePage(1); } } catch (loadError) { setError(loadError.message || "Could not load cost centres."); } };
  const loadMoreSources = async () => { const nextSourcePage = sourcePage + 1; setLoadingSources(true); setError(""); try { if (await load({ nextPage: page, nextSourcePage, appendSources: true })) setSourcePage(nextSourcePage); } catch (loadError) { setError(loadError.message || "Could not load more trips and quotes."); } finally { setLoadingSources(false); } };
  const save = async (event) => { event.preventDefault(); setError(""); setMessage(""); try { const [sourceType, sourceId] = selectedSource.split(":"); await fetchApi("/api/travel/tally/cost-centres", { method: "POST", body: JSON.stringify({ sourceType, sourceId: Number(sourceId) }), headers: { "Content-Type": "application/json" } }); setSelectedSource(""); setMessage("Cost centre saved."); await load({ nextPage: page, nextSourcePage: 1 }); setSourcePage(1); } catch (saveError) { setError(saveError.message || "Could not save cost centre."); } };
  const createMissing = async () => { setError(""); setMessage(""); setPreparing(true); try { let created = 0; for (const sourceType of ["ITINERARY", "TMC_TRIP", "QUOTE"]) { let afterSourceId = 0; let done = false; while (!done) { const result = await fetchApi("/api/travel/tally/cost-centres/prepare-missing", { method: "POST", body: JSON.stringify({ sourceType, afterSourceId, limit: 100 }), headers: { "Content-Type": "application/json" } }); created += Number(result?.created || 0); done = Boolean(result?.done); const nextAfterSourceId = Number(result?.nextAfterSourceId || 0); if (!done && nextAfterSourceId <= afterSourceId) throw new Error("Cost-centre preparation did not advance"); afterSourceId = nextAfterSourceId; } } setMessage(created ? `${created} cost centre(s) prepared.` : "All itineraries, TMC trips, and quote-only trips already have cost centres."); setPage(1); setSourcePage(1); await load({ nextPage: 1, nextSourcePage: 1 }); } catch (saveError) { setError(saveError.message || "Could not prepare missing cost centres."); } finally { setPreparing(false); } };
  const tripLabel = (row) => row.itinerary?.destination || (row.tmcTrip ? `${row.tmcTrip.tripCode} - ${row.tmcTrip.destination}` : null) || (row.quote ? `Quote for ${row.quote.contact?.name || `#${row.quote.id}`}` : null) || `${row.sourceType} #${row.sourceId}`;
  return <main className="tally-cost-centres-page"><TallySectionNav /><div className="tally-cost-centres-eyebrow">FINANCE / TALLY</div><h1>Trip Cost Centres</h1><p className="tally-cost-centres-description">Cost centres are tracked for itineraries, TMC trips, and quote-only trips, then exported to Tally with their transactions.</p><TallyWriteGate><form onSubmit={save} className="tally-cost-centres-form"><label><span>Trip / Quote</span><select value={selectedSource} onChange={(e) => setSelectedSource(e.target.value)} required><option value="">Select trip or quote</option>{sources.map((source) => <option key={`${source.sourceType}:${source.sourceId}`} value={`${source.sourceType}:${source.sourceId}`}>{source.code} - {source.label}</option>)}</select>{hasMoreSources && <button type="button" onClick={loadMoreSources} disabled={loadingSources}>{loadingSources ? "Loading…" : "Load more trips / quotes"}</button>}</label><button type="submit">Create or Refresh</button><button type="button" onClick={createMissing} disabled={preparing}>{preparing ? "Preparing…" : "Prepare Missing"}</button></form></TallyWriteGate>{message && <p className="tally-cost-centres-message">{message}</p>}{error && <p role="alert" className="tally-cost-centres-error">{error}</p>}<div className="tally-cost-centres-table-wrap"><table className="tally-cost-centres-table"><thead><tr><th>Code</th><th>Name</th><th>Trip / Quote</th><th>Status</th><th>Sync status</th><th>Action</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td>{row.code}</td><td>{row.name}</td><td>{tripLabel(row)}</td><td><span className="tally-cost-centres-badge tally-cost-centres-badge--active">{row.status}</span></td><td><span className="tally-cost-centres-badge tally-cost-centres-badge--sync">{row.syncStatus}</span></td><td>Built-in</td></tr>) : <tr><td colSpan="6">No trip cost centres yet.</td></tr>}</tbody></table></div><nav aria-label="Cost centre pages" className="tally-cost-centres-pagination"><button type="button" disabled={page <= 1} onClick={() => changePage(page - 1)}>Previous</button><span>Page {page}</span><button type="button" disabled={!hasMoreRows} onClick={() => changePage(page + 1)}>Next</button></nav></main>;
}
