import { useEffect, useState } from "react";
import TallySectionNav from "./TallySectionNav";
import { fetchApi } from "../../../utils/api";

export default function TallySyncHistoryPage() {
  const [history, setHistory] = useState([]);
  const [selected, setSelected] = useState(null);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [sourceType, setSourceType] = useState("");
  useEffect(() => { const load = () => fetchApi("/api/travel/tally/sync-history").then((data) => setHistory(data?.history || [])); load(); const timer = setInterval(load, 30000); return () => clearInterval(timer); }, []);
  const filteredHistory = history.filter((row) => { const text = [row.queue?.reference, row.queue?.partyName, row.sourceType, row.voucherType, row.status].filter(Boolean).join(" ").toLowerCase(); return (!search || text.includes(search.toLowerCase())) && (!status || row.status === status) && (!sourceType || row.sourceType === sourceType); });
  const sourceTypes = [...new Set(history.map((row) => row.sourceType).filter(Boolean))].sort();
  return <main style={{ padding: 24, maxWidth: 1280, margin: "0 auto" }}><TallySectionNav /><h1>Sync History</h1><p style={{ color: "var(--text-secondary)" }}>Local preparation and retry activity. Live Tally responses will appear after connection is enabled.</p><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 8, margin: "14px 0" }}><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search reference, party, status" aria-label="Search sync history" /><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter history status"><option value="">All statuses</option>{[...new Set(history.map((row) => row.status).filter(Boolean))].sort().map((value) => <option key={value} value={value}>{value}</option>)}</select><select value={sourceType} onChange={(event) => setSourceType(event.target.value)} aria-label="Filter history source"><option value="">All sources</option>{sourceTypes.map((value) => <option key={value} value={value}>{value}</option>)}</select></div><div style={{ overflowX: "auto" }}><table><thead><tr><th>Date</th><th>Reference</th><th>Source</th><th>Voucher</th><th>Tally voucher</th><th>Status</th><th>Details</th></tr></thead><tbody>{filteredHistory.length ? filteredHistory.map((row) => <tr key={row.id}><td>{new Date(row.createdAt).toLocaleString()}</td><td>{row.queue?.reference || `#${row.sourceId}`}</td><td>{row.sourceType}</td><td>{row.voucherType}</td><td>{row.tallyVoucherNumber || row.tallyVoucherId || "—"}</td><td>{row.status}</td><td><button type="button" onClick={() => setSelected(row)}>View</button></td></tr>) : <tr><td colSpan="7">No sync activity matches these filters.</td></tr>}</tbody></table></div>{selected && <section style={panelStyle}><div style={{ display: "flex", justifyContent: "space-between" }}><h2>Sync Detail</h2><button type="button" onClick={() => setSelected(null)}>Close</button></div><p><strong>Reference:</strong> {selected.queue?.reference || `#${selected.sourceId}`} · <strong>Party:</strong> {selected.queue?.partyName || "—"} · <strong>Amount:</strong> {selected.queue?.amount ?? "—"}</p><p><strong>Triggered by user:</strong> {selected.triggeredByUserId || "System"}</p><h3>Request payload</h3><pre style={{ overflow: "auto", whiteSpace: "pre-wrap" }}>{selected.requestPayload || "No request payload recorded."}</pre><h3>Response</h3><pre style={{ overflow: "auto", whiteSpace: "pre-wrap" }}>{selected.responsePayload || "No Tally response recorded (connection deferred)."}</pre></section>}</main>;
}

const panelStyle = { marginTop: 20, padding: 18, border: "1px solid var(--border-color, rgba(148,163,184,.2))", borderRadius: 12 };
