// @ts-check
/**
 * Gate spec — TMC trip microsite (admin CRUD + public info endpoint).
 *
 * Pins the Day 10 commit. The microsite is the public-facing trip
 * page that lives on trip-<tripCode>.tmc.travelstall.in per Q21.
 * Parents/teachers landing on this URL hit
 * /api/travel/microsites/public/:uuid without auth.
 *
 * Locked invariants:
 *   - publicUuid auto-generated by the route (UUID v4); admin doesn't
 *     pass it.
 *   - One microsite per trip (schema @unique([tripId])) — second POST
 *     returns 409 MICROSITE_EXISTS with the existing id for amend.
 *   - Public endpoint returns only PUBLIC_SELECT fields (no PII).
 *   - Public endpoint returns 410 GONE when expiresAt has passed.
 *   - Public endpoint 400s on garbage-token URLs (UUID-shape guard).
 *   - Server-side global-auth allowlist includes /travel/microsites/public.
 *
 * Out of scope (Day 11):
 *   - OTP-gated /microsites/public/:uuid/full read for PII.
 */

const { test, expect } = require("@playwright/test");

test.describe.configure({ mode: "serial" });

const BASE_URL = process.env.BASE_URL || "https://crm.globusdemos.com";
const REQUEST_TIMEOUT = 60000;
const RUN_TAG = `E2E_TRAVEL_MS_${Date.now()}`;

let travelAdminToken = null;
let genericAdminToken = null;
let tripId = null;
let schoolContactId = null;
let micrositeUuid = null;

async function loginAs(request, email, password) {
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const r = await request.post(`${BASE_URL}/api/auth/login`, {
        data: { email, password },
        headers: { "Content-Type": "application/json" },
        timeout: REQUEST_TIMEOUT,
      });
      if (r.ok()) return (await r.json()).token;
    } catch (_e) { if (attempt === 0) continue; }
  }
  return null;
}

async function getTravelAdmin(request) {
  if (!travelAdminToken) {
    travelAdminToken = await loginAs(request, "yasin@travelstall.in", "password123");
  }
  return travelAdminToken;
}
async function getGenericAdmin(request) {
  if (!genericAdminToken) {
    genericAdminToken = await loginAs(request, "admin@globussoft.com", "password123");
  }
  return genericAdminToken;
}

const headers = (token) => ({ Authorization: `Bearer ${token}`, "Content-Type": "application/json" });

async function retryOn5xx(fn) {
  let r;
  for (let attempt = 0; attempt < 3; attempt++) {
    r = await fn();
    if (r.status() < 500) return r;
    await new Promise((res) => setTimeout(res, 500 * (attempt + 1)));
  }
  return r;
}

async function get(request, token, path) {
  return retryOn5xx(() => request.get(`${BASE_URL}${path}`, { headers: headers(token), timeout: REQUEST_TIMEOUT }));
}
async function post(request, token, path, body) {
  return retryOn5xx(() => request.post(`${BASE_URL}${path}`, { headers: headers(token), data: body ?? {}, timeout: REQUEST_TIMEOUT }));
}
async function patch(request, token, path, body) {
  return retryOn5xx(() => request.patch(`${BASE_URL}${path}`, { headers: headers(token), data: body ?? {}, timeout: REQUEST_TIMEOUT }));
}
async function del(request, token, path) {
  return retryOn5xx(() => request.delete(`${BASE_URL}${path}`, { headers: headers(token), timeout: REQUEST_TIMEOUT }));
}

test.beforeAll(async ({ request }) => {
  const token = await getTravelAdmin(request);
  if (!token) return;
  // Create a school Contact + a Trip to host the microsite.
  const cRes = await post(request, token, "/api/contacts", {
    name: `${RUN_TAG} Bharat Public School`,
    email: `${RUN_TAG.toLowerCase()}-school@e2e.test`,
    phone: `+91${String(Date.now()).slice(-10)}`,
    subBrand: "tmc",
  });
  if (cRes.ok()) {
    schoolContactId = (await cRes.json()).id;
  }
  if (!schoolContactId) return;
  const tRes = await post(request, token, "/api/travel/trips", {
    tripCode: `${RUN_TAG.toLowerCase()}_trip`,
    schoolContactId,
    destination: `${RUN_TAG} Bali Ed Tour`,
    departDate: "2026-09-01",
    returnDate: "2026-09-10",
  });
  if (tRes.ok()) {
    tripId = (await tRes.json()).id;
  }
});

test.afterAll(async ({ request }) => {
  const token = await getTravelAdmin(request);
  if (!token) return;
  // DELETE on the trip cascades through the microsite via @relation
  // onDelete: Cascade in the schema.
  if (tripId) {
    await del(request, token, `/api/travel/trips/${tripId}`).catch(() => {});
  }
  if (schoolContactId) {
    await del(request, token, `/api/contacts/${schoolContactId}`).catch(() => {});
  }
});

// ─── Guards ──────────────────────────────────────────────────────────

test.describe("Travel microsites API — guards", () => {
  test("POST /trips/:id/microsite rejects generic admin with 403 WRONG_VERTICAL", async ({ request }) => {
    const token = await getGenericAdmin(request);
    if (!token || !tripId) test.skip(true, "deps missing");
    const res = await post(request, token, `/api/travel/trips/${tripId}/microsite`, {
      itineraryHtml: "<p>x</p>",
    });
    expect(res.status()).toBe(403);
    expect((await res.json()).code).toBe("WRONG_VERTICAL");
  });

  test("POST /trips/:id/microsite without auth → 401/403", async ({ request }) => {
    if (!tripId) test.skip(true, "no trip");
    const res = await request.post(`${BASE_URL}/api/travel/trips/${tripId}/microsite`, {
      data: { itineraryHtml: "<p>x</p>" },
      headers: { "Content-Type": "application/json" },
      timeout: REQUEST_TIMEOUT,
    });
    expect([401, 403]).toContain(res.status());
  });
});

// ─── Admin CRUD ──────────────────────────────────────────────────────

test.describe("Travel microsites API — admin CRUD", () => {
  test("POST creates microsite + auto-generates publicUuid", async ({ request }) => {
    const token = await getTravelAdmin(request);
    expect(tripId, "trip must be created in beforeAll").toBeTruthy();
    const res = await post(request, token, `/api/travel/trips/${tripId}/microsite`, {
      itineraryHtml: `<h1>${RUN_TAG} Trip itinerary</h1>`,
      faqJson: JSON.stringify([{ q: "When?", a: "Sept 2026" }]),
    });
    expect(res.status(), `create: ${await res.text()}`).toBe(201);
    const body = await res.json();
    expect(body.publicUuid).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(body.subdomain).toContain("trip-");
    expect(body.publishedAt).toBeTruthy();
    micrositeUuid = body.publicUuid;
  });

  test("POST again returns 409 MICROSITE_EXISTS (one-per-trip invariant)", async ({ request }) => {
    const token = await getTravelAdmin(request);
    if (!tripId) test.skip(true, "no trip");
    const res = await post(request, token, `/api/travel/trips/${tripId}/microsite`, {
      itineraryHtml: "<p>second attempt</p>",
    });
    expect(res.status()).toBe(409);
    const body = await res.json();
    expect(body.code).toBe("MICROSITE_EXISTS");
    expect(body.micrositeId).toBeTruthy();
  });

  test("POST without itineraryHtml → 400 MISSING_FIELDS", async ({ request }) => {
    const token = await getTravelAdmin(request);
    if (!tripId) test.skip(true, "no trip");
    // Use a different trip path to avoid the EXISTS short-circuit
    const fakeTripPath = `/api/travel/trips/9999999/microsite`;
    const res = await post(request, token, fakeTripPath, {});
    // Will 404 on the trip lookup before MISSING_FIELDS fires — that's fine,
    // assertion is that without-itineraryHtml NEVER succeeds with 201.
    expect(res.status()).not.toBe(201);
  });

  test("GET admin fetch returns the microsite", async ({ request }) => {
    const token = await getTravelAdmin(request);
    if (!tripId) test.skip(true, "no trip");
    const res = await get(request, token, `/api/travel/trips/${tripId}/microsite`);
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(body.tripId).toBe(tripId);
  });

  test("PATCH amends itineraryHtml + faqJson", async ({ request }) => {
    const token = await getTravelAdmin(request);
    if (!tripId) test.skip(true, "no trip");
    const res = await patch(request, token, `/api/travel/trips/${tripId}/microsite`, {
      itineraryHtml: `<h1>${RUN_TAG} Updated</h1>`,
    });
    expect(res.status()).toBe(200);
    expect((await res.json()).itineraryHtml).toContain("Updated");
  });

  test("PATCH with empty body → 400 EMPTY_BODY", async ({ request }) => {
    const token = await getTravelAdmin(request);
    if (!tripId) test.skip(true, "no trip");
    const res = await patch(request, token, `/api/travel/trips/${tripId}/microsite`, {});
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("EMPTY_BODY");
  });
});

// ─── Public endpoint (no auth) ──────────────────────────────────────

test.describe("Travel microsites API — public info endpoint", () => {
  test("GET /microsites/public/:uuid works without auth", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite uuid");
    // NO Authorization header — confirms the openPath allowlist works.
    const res = await retryOn5xx(() =>
      request.get(`${BASE_URL}/api/travel/microsites/public/${micrositeUuid}`, {
        timeout: REQUEST_TIMEOUT,
      }),
    );
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(body.publicUuid).toBe(micrositeUuid);
    expect(body.itineraryHtml).toBeTruthy();
    expect(body.trip).toBeTruthy();
    expect(body.trip.destination).toBeTruthy();
    // CRITICAL — public endpoint must NOT leak PII / trip-internal data.
    expect(body.tripId).toBeUndefined();
    expect(body.tenantId).toBeUndefined();
    expect(body.trip.schoolContactId).toBeUndefined();
    expect(body.trip.id).toBeUndefined();
  });

  test("GET /microsites/public/<garbage> → 400 INVALID_UUID", async ({ request }) => {
    const res = await request.get(`${BASE_URL}/api/travel/microsites/public/not-a-uuid`, {
      timeout: REQUEST_TIMEOUT,
    });
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("INVALID_UUID");
  });

  test("GET /microsites/public/<unknown-uuid> → 404 NOT_FOUND", async ({ request }) => {
    const res = await request.get(
      `${BASE_URL}/api/travel/microsites/public/00000000-0000-0000-0000-000000000000`,
      { timeout: REQUEST_TIMEOUT },
    );
    expect(res.status()).toBe(404);
    expect((await res.json()).code).toBe("NOT_FOUND");
  });

  test("GET /microsites/public/:uuid after expiry → 410 GONE", async ({ request }) => {
    const token = await getTravelAdmin(request);
    if (!tripId || !micrositeUuid) test.skip(true, "deps missing");
    // Move expiresAt to the past.
    await patch(request, token, `/api/travel/trips/${tripId}/microsite`, {
      expiresAt: "2020-01-01T00:00:00Z",
    });
    const res = await request.get(`${BASE_URL}/api/travel/microsites/public/${micrositeUuid}`, {
      timeout: REQUEST_TIMEOUT,
    });
    expect(res.status()).toBe(410);
    expect((await res.json()).code).toBe("GONE");
    // Restore for downstream tests / future runs
    await patch(request, token, `/api/travel/trips/${tripId}/microsite`, {
      expiresAt: null,
    });
  });
});

// ─── Image upload (Phase 1.5 / 8d — inline microsite editor) ─────────
//
// The editor's "Insert image" toolbar button POSTs a multipart file to
// /trips/:tripId/microsite/upload and embeds the returned URL into the
// itineraryHtml via <img src="…">. Mirrors the booking_pages upload
// pattern (PNG/JPEG/WebP, 4MB cap, multer disk storage under
// /uploads/microsites/).
//
// Tiny 1×1 PNG payload — enough for the route to write a file, return
// the URL, and let us assert the contract. We don't fetch the asset back
// because the static /uploads mount is served by Nginx on demo and the
// Express static mount in CI; either way the route contract is what we
// pin here.
const ONE_PX_PNG = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkAAIAAAoAAv/lxKUAAAAASUVORK5CYII=",
  "base64",
);
const TINY_TXT = Buffer.from("not an image", "utf8");

test.describe("Travel microsites API — image upload", () => {
  test("POST /microsite/upload without auth → 401/403", async ({ request }) => {
    if (!tripId) test.skip(true, "no trip");
    const res = await request.post(
      `${BASE_URL}/api/travel/trips/${tripId}/microsite/upload`,
      {
        multipart: { file: { name: "x.png", mimeType: "image/png", buffer: ONE_PX_PNG } },
        timeout: REQUEST_TIMEOUT,
      },
    );
    expect([401, 403]).toContain(res.status());
  });

  test("POST /microsite/upload rejects generic admin with 403 WRONG_VERTICAL", async ({ request }) => {
    const token = await getGenericAdmin(request);
    if (!token || !tripId) test.skip(true, "deps missing");
    const res = await request.post(
      `${BASE_URL}/api/travel/trips/${tripId}/microsite/upload`,
      {
        headers: { Authorization: `Bearer ${token}` },
        multipart: { file: { name: "x.png", mimeType: "image/png", buffer: ONE_PX_PNG } },
        timeout: REQUEST_TIMEOUT,
      },
    );
    expect(res.status()).toBe(403);
    expect((await res.json()).code).toBe("WRONG_VERTICAL");
  });

  test("POST /microsite/upload happy path returns { success, url } under /uploads/microsites/", async ({ request }) => {
    const token = await getTravelAdmin(request);
    if (!token || !tripId) test.skip(true, "deps missing");
    const res = await request.post(
      `${BASE_URL}/api/travel/trips/${tripId}/microsite/upload`,
      {
        headers: { Authorization: `Bearer ${token}` },
        multipart: { file: { name: "x.png", mimeType: "image/png", buffer: ONE_PX_PNG } },
        timeout: REQUEST_TIMEOUT,
      },
    );
    expect(res.status(), `upload: ${await res.text()}`).toBe(201);
    const body = await res.json();
    expect(body.success).toBe(true);
    expect(body.url).toMatch(/^\/uploads\/microsites\/ms-[a-z0-9-]+\.(png|jpg|jpeg|webp)$/i);
    expect(body.tripId).toBe(tripId);
  });

  test("POST /microsite/upload rejects non-image mimetype with 400 INVALID_FILE", async ({ request }) => {
    const token = await getTravelAdmin(request);
    if (!token || !tripId) test.skip(true, "deps missing");
    const res = await request.post(
      `${BASE_URL}/api/travel/trips/${tripId}/microsite/upload`,
      {
        headers: { Authorization: `Bearer ${token}` },
        multipart: { file: { name: "x.txt", mimeType: "text/plain", buffer: TINY_TXT } },
        timeout: REQUEST_TIMEOUT,
      },
    );
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("INVALID_FILE");
  });

  test("POST /microsite/upload with no file field → 400 MISSING_FILE", async ({ request }) => {
    const token = await getTravelAdmin(request);
    if (!token || !tripId) test.skip(true, "deps missing");
    // Empty multipart — multer.single("file") leaves req.file undefined.
    const res = await request.post(
      `${BASE_URL}/api/travel/trips/${tripId}/microsite/upload`,
      {
        headers: { Authorization: `Bearer ${token}` },
        multipart: { unused: "x" },
        timeout: REQUEST_TIMEOUT,
      },
    );
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("MISSING_FILE");
  });

  test("POST /microsite/upload for unknown tripId → 404 TRIP_NOT_FOUND", async ({ request }) => {
    const token = await getTravelAdmin(request);
    if (!token) test.skip(true, "no token");
    const res = await request.post(
      `${BASE_URL}/api/travel/trips/99999999/microsite/upload`,
      {
        headers: { Authorization: `Bearer ${token}` },
        multipart: { file: { name: "x.png", mimeType: "image/png", buffer: ONE_PX_PNG } },
        timeout: REQUEST_TIMEOUT,
      },
    );
    expect(res.status()).toBe(404);
    expect((await res.json()).code).toBe("TRIP_NOT_FOUND");
  });
});

// ─── PRD §4.5 — public OTP flow + gated /full reveal ─────────────────
//
// The verify-otp happy path can't be exercised end-to-end without
// reading the server-logged stub code; we cover the request-otp +
// /full contract here and leave the actual code-match path to a
// unit-level test. When Wati creds land per Q9, a sandbox phone
// number can be added that returns the OTP in the response for
// integration testing.

test.describe("Travel microsites API — OTP flow (PRD §4.5)", () => {
  test("request-otp without phone → 400 MISSING_FIELDS", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite from earlier tests");
    const res = await request.post(
      `${BASE_URL}/api/travel/microsites/public/${micrositeUuid}/request-otp`,
      {
        headers: { "Content-Type": "application/json" },
        data: { purpose: "registration" },
        timeout: REQUEST_TIMEOUT,
      },
    );
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("MISSING_FIELDS");
  });

  test("request-otp with bad purpose → 400 INVALID_PURPOSE", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite from earlier tests");
    const res = await request.post(
      `${BASE_URL}/api/travel/microsites/public/${micrositeUuid}/request-otp`,
      {
        headers: { "Content-Type": "application/json" },
        data: { phone: "+919999999999", purpose: "wormhole" },
        timeout: REQUEST_TIMEOUT,
      },
    );
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("INVALID_PURPOSE");
  });

  test("request-otp with garbage UUID → 400 INVALID_UUID", async ({ request }) => {
    const res = await request.post(
      `${BASE_URL}/api/travel/microsites/public/not-a-uuid/request-otp`,
      {
        headers: { "Content-Type": "application/json" },
        data: { phone: "+919999999999", purpose: "registration" },
        timeout: REQUEST_TIMEOUT,
      },
    );
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("INVALID_UUID");
  });

  test("request-otp for unknown microsite → 404 NOT_FOUND", async ({ request }) => {
    const res = await request.post(
      `${BASE_URL}/api/travel/microsites/public/00000000-0000-0000-0000-000000000000/request-otp`,
      {
        headers: { "Content-Type": "application/json" },
        data: { phone: "+919999999999", purpose: "registration" },
        timeout: REQUEST_TIMEOUT,
      },
    );
    expect(res.status()).toBe(404);
    expect((await res.json()).code).toBe("NOT_FOUND");
  });

  test("request-otp happy path → 201 with expiresAt + no code in response", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite from earlier tests");
    const res = await request.post(
      `${BASE_URL}/api/travel/microsites/public/${micrositeUuid}/request-otp`,
      {
        headers: { "Content-Type": "application/json" },
        // Unique phone per RUN to avoid the 60s cooldown stomping the test.
        data: { phone: `+91${String(Date.now()).slice(-10)}`, purpose: "registration" },
        timeout: REQUEST_TIMEOUT,
      },
    );
    expect(res.status(), `body: ${await res.text()}`).toBe(201);
    const body = await res.json();
    expect(body.sent).toBe(true);
    expect(body.expiresAt).toBeTruthy();
    // OTP code MUST NOT be in the response — it's stub-logged server-side.
    expect(body).not.toHaveProperty("code");
    expect(body).not.toHaveProperty("otp");
  });

  test("request-otp cooldown: second request for same tuple within 60s → 429 OTP_COOLDOWN", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite from earlier tests");
    const phone = `+91${String(Date.now() + 1).slice(-10)}`;
    const first = await request.post(
      `${BASE_URL}/api/travel/microsites/public/${micrositeUuid}/request-otp`,
      {
        headers: { "Content-Type": "application/json" },
        data: { phone, purpose: "payment-plan" },
        timeout: REQUEST_TIMEOUT,
      },
    );
    expect(first.status()).toBe(201);
    const second = await request.post(
      `${BASE_URL}/api/travel/microsites/public/${micrositeUuid}/request-otp`,
      {
        headers: { "Content-Type": "application/json" },
        data: { phone, purpose: "payment-plan" },
        timeout: REQUEST_TIMEOUT,
      },
    );
    expect(second.status()).toBe(429);
    expect((await second.json()).code).toBe("OTP_COOLDOWN");
  });

  test("verify-otp with bogus code → 400 OTP_INVALID", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite from earlier tests");
    const phone = `+91${String(Date.now() + 2).slice(-10)}`;
    // Request first so a real OTP row exists for this phone.
    await request.post(
      `${BASE_URL}/api/travel/microsites/public/${micrositeUuid}/request-otp`,
      {
        headers: { "Content-Type": "application/json" },
        data: { phone, purpose: "document-checklist" },
        timeout: REQUEST_TIMEOUT,
      },
    );
    const res = await request.post(
      `${BASE_URL}/api/travel/microsites/public/${micrositeUuid}/verify-otp`,
      {
        headers: { "Content-Type": "application/json" },
        data: { phone, purpose: "document-checklist", code: "9999" },
        timeout: REQUEST_TIMEOUT,
      },
    );
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("OTP_INVALID");
  });

  test("verify-otp without phone → 400 MISSING_FIELDS", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite");
    const res = await request.post(
      `${BASE_URL}/api/travel/microsites/public/${micrositeUuid}/verify-otp`,
      {
        headers: { "Content-Type": "application/json" },
        data: { purpose: "registration", code: "1234" },
        timeout: REQUEST_TIMEOUT,
      },
    );
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("MISSING_FIELDS");
  });

  test("/full without token → 401 TOKEN_REQUIRED", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite");
    const res = await request.get(
      `${BASE_URL}/api/travel/microsites/public/${micrositeUuid}/full`,
      { timeout: REQUEST_TIMEOUT },
    );
    expect(res.status()).toBe(401);
    expect((await res.json()).code).toBe("TOKEN_REQUIRED");
  });

  test("/full with garbage token → 401 TOKEN_INVALID", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite");
    const res = await request.get(
      `${BASE_URL}/api/travel/microsites/public/${micrositeUuid}/full?token=not-a-jwt`,
      { timeout: REQUEST_TIMEOUT },
    );
    expect(res.status()).toBe(401);
    expect((await res.json()).code).toBe("TOKEN_INVALID");
  });

  test("/full with invalid UUID → 400 INVALID_UUID", async ({ request }) => {
    const res = await request.get(
      `${BASE_URL}/api/travel/microsites/public/garbage/full?token=anything`,
      { timeout: REQUEST_TIMEOUT },
    );
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("INVALID_UUID");
  });
});

// ─── PRD §4.5 + §4.7 — public Aadhaar / DigiLocker verification ──────
//
// Parent-facing flow on the public microsite. NO app-side OTP gate —
// DigiLocker authenticates the individual during its own consent flow. We
// pin the public participant list + the contract error paths; the stub
// exchange itself is unit-covered in
// backend/test/services/digilockerClient.test.js.
const AADHAAR_PUBLIC = (uuid) => `${BASE_URL}/api/travel/microsites/public/${uuid}/verify/aadhaar`;
const PARTICIPANTS_PUBLIC = (uuid) => `${BASE_URL}/api/travel/microsites/public/${uuid}/participants`;

test.describe("Travel microsites API — Aadhaar verification (public)", () => {
  test("GET /participants → 200 with a participants array, no passport/DOB PII", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite from earlier tests");
    const res = await request.get(PARTICIPANTS_PUBLIC(micrositeUuid), { timeout: REQUEST_TIMEOUT });
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(Array.isArray(body.participants)).toBe(true);
    // Minimal projection only — never passport / DOB on the public list.
    for (const p of body.participants) {
      expect(p).not.toHaveProperty("passportNumber");
      expect(p).not.toHaveProperty("dob");
    }
  });

  test("GET /participants with garbage UUID → 400 INVALID_UUID", async ({ request }) => {
    const res = await request.get(PARTICIPANTS_PUBLIC("not-a-uuid"), { timeout: REQUEST_TIMEOUT });
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("INVALID_UUID");
  });

  test("start without participantId → 400 MISSING_FIELDS (no OTP required)", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite");
    // No Authorization header, no token — confirms the route is publicly
    // reachable (openPath) and needs only a participantId.
    const res = await request.post(`${AADHAAR_PUBLIC(micrositeUuid)}/start`, {
      headers: { "Content-Type": "application/json" },
      data: {},
      timeout: REQUEST_TIMEOUT,
    });
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("MISSING_FIELDS");
  });

  test("start with a bogus participantId → 404 PARTICIPANT_NOT_FOUND", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite");
    const res = await request.post(`${AADHAAR_PUBLIC(micrositeUuid)}/start`, {
      headers: { "Content-Type": "application/json" },
      data: { participantId: 9999999 },
      timeout: REQUEST_TIMEOUT,
    });
    expect(res.status()).toBe(404);
    expect((await res.json()).code).toBe("PARTICIPANT_NOT_FOUND");
  });

  test("start with garbage UUID → 400 INVALID_UUID", async ({ request }) => {
    const res = await request.post(`${AADHAAR_PUBLIC("not-a-uuid")}/start`, {
      headers: { "Content-Type": "application/json" },
      data: { participantId: 1 },
      timeout: REQUEST_TIMEOUT,
    });
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("INVALID_UUID");
  });

  test("start for unknown microsite → 404 NOT_FOUND", async ({ request }) => {
    const res = await request.post(
      `${AADHAAR_PUBLIC("00000000-0000-0000-0000-000000000000")}/start`,
      { headers: { "Content-Type": "application/json" }, data: { participantId: 1 }, timeout: REQUEST_TIMEOUT },
    );
    expect(res.status()).toBe(404);
    expect((await res.json()).code).toBe("NOT_FOUND");
  });

  test("callback without state → 400 MISSING_FIELDS", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite");
    const res = await request.post(`${AADHAAR_PUBLIC(micrositeUuid)}/callback`, {
      headers: { "Content-Type": "application/json" },
      data: { code: "abc" },
      timeout: REQUEST_TIMEOUT,
    });
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("MISSING_FIELDS");
  });

  test("callback with unknown state → 404 SESSION_NOT_FOUND", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite");
    const res = await request.post(`${AADHAAR_PUBLIC(micrositeUuid)}/callback`, {
      headers: { "Content-Type": "application/json" },
      data: { state: `nonexistent-${Date.now()}`, code: "abc" },
      timeout: REQUEST_TIMEOUT,
    });
    expect(res.status()).toBe(404);
    expect((await res.json()).code).toBe("SESSION_NOT_FOUND");
  });

  test("callback with garbage UUID → 400 INVALID_UUID", async ({ request }) => {
    const res = await request.post(`${AADHAAR_PUBLIC("garbage")}/callback`, {
      headers: { "Content-Type": "application/json" },
      data: { state: "x", code: "y" },
      timeout: REQUEST_TIMEOUT,
    });
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("INVALID_UUID");
  });
});

// ─── Public document upload (Passport + Aadhaar + parent consent) ────
//
// Draft-scoped: the uploader is identified ONLY by the draftToken they
// arrive with from the landing-page registration — there is no public
// participant list, so one family can never see or touch another's data.
// This spec pins the reachable contract error paths (invalid UUID /
// unknown microsite / missing + bogus token) + the openPath reachability.
// The happy-path multipart store is covered by the frontend RTL suite +
// backend/test visaDocStore unit tests, since minting a real draftToken
// here would require driving the whole landing-page registration flow.
const DOCUMENTS_PUBLIC = (uuid) => `${BASE_URL}/api/travel/microsites/public/${uuid}/documents`;

test.describe("Travel microsites API — document upload (public)", () => {
  test("garbage UUID → 400 INVALID_UUID", async ({ request }) => {
    const res = await request.post(DOCUMENTS_PUBLIC("not-a-uuid"), {
      multipart: { draftToken: "x", consent: "true" },
      timeout: REQUEST_TIMEOUT,
    });
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("INVALID_UUID");
  });

  test("unknown microsite → 404 NOT_FOUND", async ({ request }) => {
    const res = await request.post(
      DOCUMENTS_PUBLIC("00000000-0000-0000-0000-000000000000"),
      { multipart: { draftToken: "x", consent: "true" }, timeout: REQUEST_TIMEOUT },
    );
    expect(res.status()).toBe(404);
    expect((await res.json()).code).toBe("NOT_FOUND");
  });

  test("valid microsite, missing draftToken → 400 MISSING_TOKEN", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite from earlier tests");
    const res = await request.post(DOCUMENTS_PUBLIC(micrositeUuid), {
      multipart: { consent: "true" },
      timeout: REQUEST_TIMEOUT,
    });
    expect(res.status()).toBe(400);
    expect((await res.json()).code).toBe("MISSING_TOKEN");
  });

  test("valid microsite, bogus draftToken → 404 DRAFT_NOT_FOUND", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite from earlier tests");
    const res = await request.post(DOCUMENTS_PUBLIC(micrositeUuid), {
      multipart: { draftToken: `ghost-${Date.now()}`, consent: "true" },
      timeout: REQUEST_TIMEOUT,
    });
    expect(res.status()).toBe(404);
    expect((await res.json()).code).toBe("DRAFT_NOT_FOUND");
  });

  test("route is publicly reachable — no Authorization header yields a contract error, never 401", async ({ request }) => {
    if (!micrositeUuid) test.skip(true, "no microsite from earlier tests");
    const res = await request.post(DOCUMENTS_PUBLIC(micrositeUuid), {
      multipart: { draftToken: `ghost-${Date.now()}`, consent: "true" },
      timeout: REQUEST_TIMEOUT,
    });
    // A 404 DRAFT_NOT_FOUND (not 401) proves the openPath allowlist covers
    // this endpoint — it's reached without any token.
    expect([400, 404]).toContain(res.status());
    expect(res.status()).not.toBe(401);
  });
});
