const express = require("express");
const { verifyToken, verifyRole } = require("../middleware/auth");
const crypto = require("crypto");
const PDFDocument = require("pdfkit");

const router = express.Router();
const prisma = require("../lib/prisma");

// Fetch all ledgers for current tenant
router.get("/", verifyToken, async (req, res) => {
  try {
    const invoices = await prisma.invoice.findMany({
      where: { tenantId: req.user.tenantId },
      include: { contact: true, deal: true },
      orderBy: [{ status: "desc" }, { dueDate: "asc" }]
    });
    res.json(invoices);
  } catch (err) {
    res.status(500).json({ error: "Failed to locate invoice ledger" });
  }
});

// Draft new Invoice
router.post("/", verifyToken, verifyRole(["ADMIN", "MANAGER"]), async (req, res) => {
  try {
    const { amount, dueDate, contactId, dealId } = req.body;
    const invNum = `INV-${crypto.randomBytes(3).toString("hex").toUpperCase()}`;

    const invoice = await prisma.invoice.create({
      data: {
        invoiceNum: invNum,
        amount: parseFloat(amount),
        dueDate: new Date(dueDate),
        contactId: parseInt(contactId),
        dealId: dealId ? parseInt(dealId) : null,
        tenantId: req.user.tenantId,
      },
      include: { contact: true, deal: true }
    });
    res.status(201).json(invoice);
  } catch (err) {
    res.status(500).json({ error: "Invoice compilation and issuance failed" });
  }
});

// Reconcile Payment (Mark as Paid)
router.put("/:id/pay", verifyToken, async (req, res) => {
  try {
    const existing = await prisma.invoice.findFirst({ where: { id: parseInt(req.params.id), tenantId: req.user.tenantId } });
    if (!existing) return res.status(404).json({ error: "Invoice not found" });
    const invoice = await prisma.invoice.update({
      where: { id: existing.id },
      data: { status: "PAID" },
      include: { contact: true }
    });
    res.json(invoice);
  } catch (err) {
    res.status(500).json({ error: "Payment reconciliation operation failed" });
  }
});

// Generate Invoice PDF
router.get("/:id/pdf", verifyToken, async (req, res) => {
  try {
    const invoice = await prisma.invoice.findFirst({
      where: { id: parseInt(req.params.id), tenantId: req.user.tenantId },
      include: { contact: true },
    });
    if (!invoice) return res.status(404).json({ error: "Invoice not found" });

    const doc = new PDFDocument({ size: "A4", margin: 50 });

    const filename = `${invoice.invoiceNum || "INV-" + invoice.id}.pdf`;
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename=${filename}`);
    doc.pipe(res);

    // Header
    doc.fontSize(24).font("Helvetica-Bold").text("Globussoft CRM", 50, 50);
    doc.fontSize(10).font("Helvetica").fillColor("#666666")
      .text("Enterprise Invoice", 50, 80);

    // Invoice details box
    doc.fillColor("#000000").fontSize(14).font("Helvetica-Bold")
      .text(`Invoice: ${invoice.invoiceNum || "N/A"}`, 50, 130);

    doc.fontSize(10).font("Helvetica").fillColor("#333333");
    const statusLabel = invoice.status || "UNPAID";
    doc.text(`Status: ${statusLabel}`, 50, 155);
    doc.text(`Issue Date: ${new Date(invoice.createdAt).toLocaleDateString()}`, 50, 172);
    doc.text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`, 50, 189);

    // Contact info
    doc.fontSize(12).font("Helvetica-Bold").fillColor("#000000")
      .text("Bill To:", 50, 225);
    doc.fontSize(10).font("Helvetica").fillColor("#333333")
      .text(invoice.contact?.name || "Unknown Contact", 50, 245)
      .text(invoice.contact?.email || "", 50, 260)
      .text(invoice.contact?.company || "", 50, 275);

    // Line separator
    doc.moveTo(50, 310).lineTo(545, 310).strokeColor("#cccccc").stroke();

    // Amount table header
    doc.fillColor("#ffffff").rect(50, 325, 495, 30).fill("#3b82f6");
    doc.fillColor("#ffffff").fontSize(10).font("Helvetica-Bold")
      .text("Description", 60, 333)
      .text("Amount", 450, 333, { width: 85, align: "right" });

    // Amount row
    doc.fillColor("#333333").font("Helvetica").fontSize(10)
      .text("Invoice Charge", 60, 370)
      .text(`$${Number(invoice.amount).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 450, 370, { width: 85, align: "right" });

    // Total
    doc.moveTo(50, 400).lineTo(545, 400).strokeColor("#cccccc").stroke();
    doc.font("Helvetica-Bold").fontSize(12).fillColor("#000000")
      .text("Total:", 350, 415)
      .text(`$${Number(invoice.amount).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 450, 415, { width: 85, align: "right" });

    // Footer
    doc.fontSize(8).font("Helvetica").fillColor("#999999")
      .text("Generated by Globussoft CRM", 50, 750, { align: "center" });

    doc.end();
  } catch (err) {
    console.error("[PDF Generation Error]:", err);
    res.status(500).json({ error: "Failed to generate invoice PDF" });
  }
});

// Set invoice as recurring
router.put("/:id/recurring", verifyToken, async (req, res) => {
  try {
    const { isRecurring, recurFrequency } = req.body;
    const invoice = await prisma.invoice.findFirst({ where: { id: parseInt(req.params.id), tenantId: req.user.tenantId } });
    if (!invoice) return res.status(404).json({ error: "Invoice not found" });

    const nextDate = isRecurring ? new Date() : null;
    if (nextDate && recurFrequency) {
      switch (recurFrequency) {
        case "monthly": nextDate.setMonth(nextDate.getMonth() + 1); break;
        case "quarterly": nextDate.setMonth(nextDate.getMonth() + 3); break;
        case "yearly": nextDate.setFullYear(nextDate.getFullYear() + 1); break;
      }
    }

    const updated = await prisma.invoice.update({
      where: { id: invoice.id },
      data: { isRecurring: !!isRecurring, recurFrequency: recurFrequency || null, nextRecurDate: nextDate },
      include: { contact: true }
    });
    res.json(updated);
  } catch (err) {
    res.status(500).json({ error: "Failed to update recurring status" });
  }
});

// Obliterate Invoice
// Void invoice — soft-void: status flips to VOIDED, row + audit trail preserved.
// This is what the UI's "Void" button now calls. The hard DELETE below remains
// for admin/cleanup use but is no longer reachable from the standard ledger UI.
router.put("/:id/void", verifyToken, verifyRole(["ADMIN", "MANAGER"]), async (req, res) => {
  try {
    const existing = await prisma.invoice.findFirst({ where: { id: parseInt(req.params.id), tenantId: req.user.tenantId } });
    if (!existing) return res.status(404).json({ error: "Invoice not found" });
    if (existing.status === "PAID") return res.status(400).json({ error: "Cannot void a paid invoice" });
    const invoice = await prisma.invoice.update({
      where: { id: existing.id },
      data: { status: "VOIDED" },
      include: { contact: true, deal: true }
    });
    res.json(invoice);
  } catch (err) {
    res.status(500).json({ error: "Failed to void invoice" });
  }
});

router.delete("/:id", verifyToken, verifyRole(["ADMIN"]), async (req, res) => {
  try {
    const existing = await prisma.invoice.findFirst({ where: { id: parseInt(req.params.id), tenantId: req.user.tenantId } });
    if (!existing) return res.status(404).json({ error: "Invoice not found" });
    await prisma.invoice.delete({ where: { id: existing.id } });
    res.json({ success: true });
  } catch(err) {
    res.status(500).json({ error: "Ledger deletion failure" });
  }
});

module.exports = router;
