// Travel CRM — Travel Stall personalised destination PDF (LLM consumer).
//
// TS18 Phase 2 SHELL (tick #185, 2026-05-24).
//
// PRD docs/TRAVEL_CRM_PRD.md §4.7 (Travel Stall family audience) +
// §9.1 (LLM routing per Q11). Customer-profile-driven destination
// recommendations generated by the lib/llmRouter.js abstraction —
// in STUB MODE today (per Q11 cred-block: API keys held by Travel
// Stall, lands under SupplierCredential category "llm-key").
//
// Cred-swap behaviour: backend/lib/llmRouter.js routes "reasoning"
// task to gemini-flash primary / gpt-4 fallback (2026-07-14 swap off
// Claude Opus). Until Q11 keys drop, the router returns deterministic
// synthetic text matching the envelope shape
// { text, finishReason, usage, model, stub:true }. The MOMENT Q11 keys
// land in ENV or SupplierCredential, this endpoint switches over to
// real Gemini Flash reasoning with NO code change here — the swap
// point is inside llmRouter.routeRequest.
//
// Endpoint: POST /api/travel-personalised-destinations/recommend
//   Body: { customerName, budgetINR, travelMonth, partySize,
//           interests?, pastDestinations? }
//   Returns: { text, finishReason, usage, model, stub, destinations }
//
// `destinations` is the structured-parse of the LLM output into an
// array of { name, summary, fitScore }. Phase 2 SHELL leaves it
// null — Phase 2.5 lands the parser once the real model is online
// and we know what its output schema looks like. The raw `text`
// field IS rendered by the caller in the meantime (and by the PDF
// renderer in a separate follow-up).
//
// PII discipline (per llmRouter.js header): the prompt + body fields
// (customerName, pastDestinations) are NEVER logged from this route.
// The router's structured log line only emits token counts. Do NOT
// add a console.log of the prompt or payload here.
//
// Auth: verifyToken + verifyRole(['ADMIN', 'MANAGER']) — operator-only.
// This is the staff-facing builder, not the public-quiz route. Public
// destination recommendations land in a separate sibling endpoint
// when Travel Stall product call resolves Q2/Q13 framing.

const express = require("express");
const router = express.Router();
const { verifyToken, verifyRole } = require("../middleware/auth");
const { requirePermission } = require("../middleware/requirePermission");
const { requireTravelTenant } = require("../middleware/travelGuards");
const prisma = require("../lib/prisma");
const llmRouter = require("../lib/llmRouter");

// Defensive budget cap so a typo / malicious caller can't trigger
// an unbounded prompt size. INR 1 crore is comfortably above any
// realistic Travel Stall family-holiday budget — anything higher
// is either error or junk.
const BUDGET_CAP_INR = 10_000_000;
const MAX_CUSTOMER_NAME_LEN = 200;
const MAX_INTERESTS = 10;
const MAX_INTEREST_LEN = 50;
const MAX_PAST_DESTINATIONS = 20;
const MAX_PAST_DESTINATION_LEN = 100;
const MIN_PARTY_SIZE = 1;
const MAX_PARTY_SIZE = 20;

const VALID_MONTHS = [
  "january", "february", "march", "april", "may", "june",
  "july", "august", "september", "october", "november", "december",
];

/**
 * Build a deterministic prompt from the customer profile. Pure
 * function — no PII logging, no side effects. The prompt format
 * pins the LLM's expected output shape (numbered list of 3-5
 * destinations with summary + fit score) so the Phase 2.5 parser
 * has stable structure to extract from.
 */
function buildPrompt(body) {
  const { customerName, budgetINR, travelMonth, partySize, interests = [], pastDestinations = [] } = body;
  const interestsLine = interests.length > 0
    ? `Interests: ${interests.join(", ")}.`
    : "Interests: not specified.";
  const pastLine = pastDestinations.length > 0
    ? `Past destinations visited: ${pastDestinations.join(", ")}.`
    : "Past destinations: none recorded.";
  return [
    `Travel Stall family-holiday recommendation request.`,
    `Customer: ${customerName}.`,
    `Party size: ${partySize}.`,
    `Travel month: ${travelMonth}.`,
    `Budget: INR ${budgetINR}.`,
    interestsLine,
    pastLine,
    ``,
    `Recommend 3 to 5 personalised destinations for this customer.`,
    `For each destination, output:`,
    `  1) <Destination name>`,
    `     Summary: <2-3 sentence rationale tied to the customer's profile>`,
    `     Fit score: <integer 0-100>`,
  ].join("\n");
}

/**
 * Validate the request body. Returns { ok: true, body } on success
 * or { ok: false, status, error, code } on failure. Doing this
 * inline keeps the handler readable and avoids importing the
 * express-validator middleware just for one endpoint.
 */
function validateBody(raw) {
  const body = raw || {};
  const { customerName, budgetINR, travelMonth, partySize, interests, pastDestinations } = body;

  if (typeof customerName !== "string" || customerName.trim().length === 0) {
    return { ok: false, status: 400, error: "customerName is required (non-empty string)", code: "INVALID_PAYLOAD" };
  }
  if (customerName.length > MAX_CUSTOMER_NAME_LEN) {
    return { ok: false, status: 400, error: `customerName must be ≤ ${MAX_CUSTOMER_NAME_LEN} chars`, code: "INVALID_PAYLOAD" };
  }

  if (!Number.isInteger(budgetINR) || budgetINR <= 0) {
    return { ok: false, status: 400, error: "budgetINR must be a positive integer", code: "INVALID_PAYLOAD" };
  }
  if (budgetINR > BUDGET_CAP_INR) {
    return { ok: false, status: 400, error: `budgetINR must be ≤ ${BUDGET_CAP_INR}`, code: "BUDGET_EXCEEDED" };
  }

  if (typeof travelMonth !== "string" || !VALID_MONTHS.includes(travelMonth.toLowerCase())) {
    return { ok: false, status: 400, error: `travelMonth must be one of: ${VALID_MONTHS.join(", ")}`, code: "INVALID_PAYLOAD" };
  }

  if (!Number.isInteger(partySize) || partySize < MIN_PARTY_SIZE || partySize > MAX_PARTY_SIZE) {
    return { ok: false, status: 400, error: `partySize must be an integer in [${MIN_PARTY_SIZE}, ${MAX_PARTY_SIZE}]`, code: "INVALID_PAYLOAD" };
  }

  // interests + pastDestinations are optional; default to [].
  let interestsArr = [];
  if (interests !== undefined && interests !== null) {
    if (!Array.isArray(interests)) {
      return { ok: false, status: 400, error: "interests must be an array of strings", code: "INVALID_PAYLOAD" };
    }
    if (interests.length > MAX_INTERESTS) {
      return { ok: false, status: 400, error: `interests must have ≤ ${MAX_INTERESTS} entries`, code: "INVALID_PAYLOAD" };
    }
    for (const it of interests) {
      if (typeof it !== "string" || it.length === 0 || it.length > MAX_INTEREST_LEN) {
        return { ok: false, status: 400, error: `each interest must be a non-empty string ≤ ${MAX_INTEREST_LEN} chars`, code: "INVALID_PAYLOAD" };
      }
    }
    interestsArr = interests;
  }

  let pastArr = [];
  if (pastDestinations !== undefined && pastDestinations !== null) {
    if (!Array.isArray(pastDestinations)) {
      return { ok: false, status: 400, error: "pastDestinations must be an array of strings", code: "INVALID_PAYLOAD" };
    }
    if (pastDestinations.length > MAX_PAST_DESTINATIONS) {
      return { ok: false, status: 400, error: `pastDestinations must have ≤ ${MAX_PAST_DESTINATIONS} entries`, code: "INVALID_PAYLOAD" };
    }
    for (const pd of pastDestinations) {
      if (typeof pd !== "string" || pd.length === 0 || pd.length > MAX_PAST_DESTINATION_LEN) {
        return { ok: false, status: 400, error: `each pastDestinations entry must be a non-empty string ≤ ${MAX_PAST_DESTINATION_LEN} chars`, code: "INVALID_PAYLOAD" };
      }
    }
    pastArr = pastDestinations;
  }

  return {
    ok: true,
    body: {
      customerName: customerName.trim(),
      budgetINR,
      travelMonth: travelMonth.toLowerCase(),
      partySize,
      interests: interestsArr,
      pastDestinations: pastArr,
    },
  };
}

// POST /api/travel-personalised-destinations/recommend
router.post(
  "/recommend",
  verifyToken,
  requirePermission("itineraries", "read"),
  async (req, res) => {
    const v = validateBody(req.body);
    if (!v.ok) {
      return res.status(v.status).json({ error: v.error, code: v.code });
    }

    const prompt = buildPrompt(v.body);

    try {
      const result = await llmRouter.routeRequest({
        task: "reasoning",
        prompt,
        // PII discipline: keep the structured fields out of the
        // payload object too — the router's own log line emits
        // token counts only, but defence-in-depth keeps PII out
        // of any future payload-printing diagnostic. Pass __userId
        // + __surface hints so the LlmCallLog row attributes
        // back to the operator + the personalised-destinations
        // surface for the admin daily-spend report.
        payload: { prompt },
        tenantId: req.user.tenantId,
        __userId: req.user.userId,
        __surface: "personalised-destinations",
      });

      return res.status(200).json({
        text: result.text,
        finishReason: result.finishReason,
        usage: result.usage,
        model: result.model,
        stub: Boolean(result.stub),
        // Phase 2 SHELL: structured parse is a no-op. Phase 2.5
        // lands a parser that lifts an array of
        //   { name: string, summary: string, fitScore: number }
        // out of `result.text` once the real model is online and
        // we've seen its output shape.
        destinations: null,
      });
    } catch (e) {
      if (e && e.code === "LLM_BUDGET_EXCEEDED") {
        return res.status(429).json({
          error: e.message,
          code: "LLM_BUDGET_EXCEEDED",
          spentCents: e.spentCents,
          capCents: e.capCents,
        });
      }
      console.error("[travel-personalised-destinations] router error:", e.message);
      return res.status(502).json({
        error: "LLM router unavailable",
        code: "LLM_ERROR",
      });
    }
  },
);

// ============================================================================
// GET /api/travel-personalised-destinations/stats
//
// PRD_TRAVEL §4.7 + §9.1 — first rollup endpoint for the admin-curated
// tailored-destinations domain. Mirrors the /suppliers/stats +
// /religious-packets/stats + /flyer-templates/global-stats posture across
// the travel rollup family.
//
// IMPORTANT — DATA SOURCE NOTE
// ----------------------------
// The personalised-destinations domain has NO Prisma model of its own —
// it is a pure LLM consumer. The persisted footprint is the LlmCallLog
// rows written by lib/llmRouter.js with surface="personalised-destinations"
// (see POST /recommend above; the router stamps __surface into the row).
// This rollup aggregates LlmCallLog where (tenantId, surface) match.
//
// Sub-brand scope: LlmCallLog has NO subBrand column — the rollup is
// tenant-wide and the response envelope omits `bySubBrand`. If a future
// schema migration adds subBrand (likely if Travel Stall ever splits
// personalised-destinations per sub-brand), this handler should grow a
// bySubBrand bucket then. Today the model is tenant-wide-only, per the
// "If the model is tenant-wide-only: skip subBrand narrowing" guidance.
//
// USER-readable: anodyne aggregate (count + last activity timestamp);
// safe. No audit row written — read-only meta surface, mirrors sibling
// /stats endpoints across the rollup family.
//
// Behaviour:
//   - tenantId-scoped (via requireTravelTenant + req.travelTenant.id)
//   - surface="personalised-destinations" narrows to THIS domain's calls
//   - ?from / ?to (ISO date bounds) filter LlmCallLog.createdAt; invalid
//     → 400 INVALID_DATE
//   - Response envelope:
//       total: number              — count of matching LlmCallLog rows
//       byTask: { <task>: count }  — task taxonomy bucket
//       byModel: { <model>: count } — which LLM model handled it
//       stubCount: number          — rows with stub=true
//       liveCount: number          — rows with stub=false
//       lastCreatedAt: ISO | null  — most-recent createdAt (skips null)
//
// Express route ordering: literal-path /stats is declared BEFORE the
// export so any future :id family added between this and module.exports
// wouldn't shadow the /stats matcher.
// ============================================================================
const PERSONALISED_DESTINATIONS_SURFACE = "personalised-destinations";

router.get(
  "/stats",
  verifyToken,
  requireTravelTenant,
  async (req, res) => {
    try {
      const tenantId = req.travelTenant.id;
      const where = {
        tenantId,
        surface: PERSONALISED_DESTINATIONS_SURFACE,
      };

      // Optional ISO date bounds on LlmCallLog.createdAt — same shape as
      // the sibling /suppliers/stats + /religious-packets/stats endpoints.
      const fromRaw = req.query.from ? String(req.query.from) : null;
      const toRaw = req.query.to ? String(req.query.to) : null;
      if (fromRaw) {
        const d = new Date(fromRaw);
        if (Number.isNaN(d.getTime())) {
          return res.status(400).json({
            error: "from must be a valid ISO date",
            code: "INVALID_DATE",
          });
        }
        where.createdAt = Object.assign(where.createdAt || {}, { gte: d });
      }
      if (toRaw) {
        const d = new Date(toRaw);
        if (Number.isNaN(d.getTime())) {
          return res.status(400).json({
            error: "to must be a valid ISO date",
            code: "INVALID_DATE",
          });
        }
        where.createdAt = Object.assign(where.createdAt || {}, { lte: d });
      }

      const rows = await prisma.llmCallLog.findMany({
        where,
        select: {
          id: true,
          task: true,
          model: true,
          stub: true,
          createdAt: true,
        },
        orderBy: [{ id: "asc" }],
      });

      // Empty short-circuit — return zeroed shape with stable bucket maps.
      if (rows.length === 0) {
        return res.json({
          total: 0,
          byTask: {},
          byModel: {},
          stubCount: 0,
          liveCount: 0,
          lastCreatedAt: null,
        });
      }

      let stubCount = 0;
      let liveCount = 0;
      let lastCreatedAt = null;
      const byTask = {};
      const byModel = {};

      for (const r of rows) {
        if (r.stub) stubCount += 1;
        else liveCount += 1;

        // Defensive: createdAt rows with null/invalid timestamps still
        // contribute to `total` but are skipped for the lastCreatedAt
        // max — same posture as sibling stats endpoints.
        if (r.createdAt != null) {
          const ts = r.createdAt instanceof Date
            ? r.createdAt
            : new Date(r.createdAt);
          if (!Number.isNaN(ts.getTime())) {
            if (!lastCreatedAt || ts > lastCreatedAt) lastCreatedAt = ts;
          }
        }

        const taskKey = r.task ? String(r.task) : "_unknown";
        if (!byTask[taskKey]) byTask[taskKey] = { count: 0 };
        byTask[taskKey].count += 1;

        const modelKey = r.model ? String(r.model) : "_unknown";
        if (!byModel[modelKey]) byModel[modelKey] = { count: 0 };
        byModel[modelKey].count += 1;
      }

      return res.json({
        total: rows.length,
        byTask,
        byModel,
        stubCount,
        liveCount,
        lastCreatedAt: lastCreatedAt ? lastCreatedAt.toISOString() : null,
      });
    } catch (e) {
      console.error("[travel-personalised-destinations] /stats error:", e.message);
      return res.status(500).json({
        error: "Failed to compute personalised-destinations stats",
        code: "STATS_ERROR",
      });
    }
  },
);

// ============================================================================
// GET /api/travel-personalised-destinations/by-month
//
// PRD_TRAVEL §4.7 + §9.1 — sibling to /stats. USER-readable, anodyne monthly
// rollup over the same LlmCallLog data source (surface="personalised-
// destinations"). Mirrors the broader by-month family (/suppliers/by-month,
// /flyer-templates/by-month, /quotes/by-month, /invoices/by-month) at the
// LLM-consumer layer.
//
// IMPORTANT — DATA SOURCE NOTE
// ----------------------------
// Same as /stats: personalised-destinations has NO Prisma model of its own.
// The aggregate is over LlmCallLog where (tenantId, surface) match. Sub-brand
// scope: LlmCallLog has NO subBrand column — rollup is tenant-wide-only;
// envelope omits `bySubBrand`. If a future schema migration adds subBrand,
// extend this handler to narrow + bucket.
//
// USER-readable: anodyne aggregate. No audit row written — read-only meta
// surface, mirrors sibling /by-month endpoints across the rollup family.
//
// Behaviour:
//   - tenantId-scoped via requireTravelTenant + req.travelTenant.id
//   - surface="personalised-destinations" narrows to this domain's calls
//   - ?from / ?to (optional inclusive YYYY-MM bounds) filter the bucket
//     array AFTER aggregation; invalid → 400 INVALID_MONTH_FORMAT
//   - ?orderBy default `month:asc`; accepts `month:{asc|desc}` and
//     `count:{asc|desc}`
//   - ?limit default 12, capped at 60; ?offset default 0
//   - JS-side aggregation into Map<"YYYY-MM", { month, count, byTask,
//     byModel, stubCount, liveCount }> keyed on UTC year+month from
//     createdAt. Null / invalid createdAt → "unknown" bucket; excluded
//     when either ?from or ?to is set
//   - Pagination AFTER aggregation + sort + bucket filter
//
// Response envelope:
//   { total: <pre-pagination bucket count>,
//     rows: [{ month, count, byTask, byModel, stubCount, liveCount }, ...] }
//
// Express route ordering: literal-path /by-month declared BEFORE any future
// /:id family so `:id="by-month"` cannot shadow this matcher.
// ============================================================================
const PERSONALISED_DEST_MONTH_RE = /^\d{4}-(0[1-9]|1[0-2])$/;

router.get(
  "/by-month",
  verifyToken,
  requireTravelTenant,
  async (req, res) => {
    try {
      const tenantId = req.travelTenant.id;

      // YYYY-MM validation — mirrors /suppliers/by-month + /flyer-templates/by-month.
      const fromRaw = req.query.from ? String(req.query.from) : null;
      const toRaw = req.query.to ? String(req.query.to) : null;
      if (fromRaw !== null && !PERSONALISED_DEST_MONTH_RE.test(fromRaw)) {
        return res.status(400).json({
          error: "from must be in YYYY-MM format",
          code: "INVALID_MONTH_FORMAT",
        });
      }
      if (toRaw !== null && !PERSONALISED_DEST_MONTH_RE.test(toRaw)) {
        return res.status(400).json({
          error: "to must be in YYYY-MM format",
          code: "INVALID_MONTH_FORMAT",
        });
      }

      const take = Math.min(parseInt(req.query.limit, 10) || 12, 60);
      const skip = parseInt(req.query.offset, 10) || 0;
      const orderByRaw = req.query.orderBy
        ? String(req.query.orderBy)
        : "month:asc";
      const VALID_ORDER_BY = new Set([
        "month:asc",
        "month:desc",
        "count:asc",
        "count:desc",
      ]);
      const orderBy = VALID_ORDER_BY.has(orderByRaw) ? orderByRaw : "month:asc";

      const where = {
        tenantId,
        surface: PERSONALISED_DESTINATIONS_SURFACE,
      };

      const rows = await prisma.llmCallLog.findMany({
        where,
        select: {
          id: true,
          task: true,
          model: true,
          stub: true,
          createdAt: true,
        },
        orderBy: [{ id: "asc" }],
      });

      // Aggregate per-UTC-month. Map "YYYY-MM" → { month, count, byTask,
      // byModel, stubCount, liveCount }. Null/invalid createdAt rows land
      // in the "unknown" bucket.
      const byMonth = new Map();
      for (const r of rows) {
        let monthKey = "unknown";
        if (r.createdAt) {
          const dt = r.createdAt instanceof Date
            ? r.createdAt
            : new Date(r.createdAt);
          if (!Number.isNaN(dt.getTime())) {
            const yyyy = dt.getUTCFullYear();
            const mm = String(dt.getUTCMonth() + 1).padStart(2, "0");
            monthKey = `${yyyy}-${mm}`;
          }
        }

        let bucket = byMonth.get(monthKey);
        if (!bucket) {
          bucket = {
            month: monthKey,
            count: 0,
            byTask: {},
            byModel: {},
            stubCount: 0,
            liveCount: 0,
          };
          byMonth.set(monthKey, bucket);
        }
        bucket.count += 1;
        if (r.stub) bucket.stubCount += 1;
        else bucket.liveCount += 1;

        const taskKey = r.task ? String(r.task) : "_unknown";
        bucket.byTask[taskKey] = (bucket.byTask[taskKey] || 0) + 1;

        const modelKey = r.model ? String(r.model) : "_unknown";
        bucket.byModel[modelKey] = (bucket.byModel[modelKey] || 0) + 1;
      }

      let months = [...byMonth.values()];

      // ?from / ?to bucket filter. "unknown" excluded when either bound is
      // set (no comparable token); preserved otherwise so the count surface
      // stays complete. Mirrors slice 24 /suppliers/by-month posture.
      if (fromRaw !== null) {
        months = months.filter(
          (r) => r.month !== "unknown" && r.month >= fromRaw,
        );
      }
      if (toRaw !== null) {
        months = months.filter(
          (r) => r.month !== "unknown" && r.month <= toRaw,
        );
      }

      // Sort. "month" sorts lexicographically on YYYY-MM (also chronological).
      // "unknown" sorts last in asc / first in desc (lexicographically >
      // "9999-12") — acceptable for a defensive fallback bucket.
      const [field, dir] = orderBy.split(":");
      const mult = dir === "asc" ? 1 : -1;
      months.sort((a, b) => {
        if (field === "month") {
          if (a.month < b.month) return -1 * mult;
          if (a.month > b.month) return 1 * mult;
          return 0;
        }
        return ((a[field] || 0) - (b[field] || 0)) * mult;
      });

      const total = months.length;
      // Pagination AFTER aggregation + sort + filter, same as slice 24.
      const paged = months.slice(skip, skip + take);

      return res.json({
        total,
        rows: paged,
      });
    } catch (e) {
      console.error(
        "[travel-personalised-destinations] /by-month error:",
        e.message,
      );
      return res.status(500).json({
        error: "Failed to compute personalised-destinations monthly rollup",
        code: "BY_MONTH_ERROR",
      });
    }
  },
);

module.exports = router;
