package middleware

import (
	"net/http"
	"strings"

	"github.com/labstack/echo/v4"
)

// SecurityHeaders replicates Helmet-style headers used by the Node backend.
// Content-Security-Policy is Report-Only with a per-request nonce.
func SecurityHeaders() echo.MiddlewareFunc {
	return func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) error {
			res := c.Response()
			headers := res.Header()
			headers.Set("X-Content-Type-Options", "nosniff")
			headers.Set("X-Frame-Options", "DENY")
			headers.Set("X-XSS-Protection", "0")
			headers.Set("Referrer-Policy", "strict-origin-when-cross-origin")
			headers.Set("Permissions-Policy", "geolocation=(), microphone=(), camera=()")
			headers.Set("Strict-Transport-Security", "max-age=15552000; includeSubDomains")
			// Report-Only CSP; nonces are generated by frontend if needed.
			headers.Set("Content-Security-Policy-Report-Only", "default-src 'self'; report-uri /api/csp/report")
			// Hide server identity.
			headers.Del("Server")
			return next(c)
		}
	}
}

// CORS returns CORS middleware matching the Node backend's permissive policy.
func CORS(allowOrigins []string) echo.MiddlewareFunc {
	return func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) error {
			req := c.Request()
			res := c.Response()
			origin := req.Header.Get("Origin")
			allowed := false
			for _, o := range allowOrigins {
				if o == "*" || strings.EqualFold(o, origin) {
					allowed = true
					break
				}
			}
			if allowed && origin != "" {
				res.Header().Set("Access-Control-Allow-Origin", origin)
			} else if allowed {
				res.Header().Set("Access-Control-Allow-Origin", "*")
			}
			res.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS")
			res.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization, X-Active-Tenant, X-Step-Up-Token, X-Request-ID")
			res.Header().Set("Access-Control-Allow-Credentials", "true")
			res.Header().Set("Access-Control-Max-Age", "86400")
			if req.Method == http.MethodOptions {
				return c.NoContent(http.StatusNoContent)
			}
			return next(c)
		}
	}
}

// OriginCheck is a lightweight guard for CSRF-sensitive mutations.
// In Phase 0 it logs and allows; stricter enforcement will mirror the Node backend.
func OriginCheck(frontendURL string) echo.MiddlewareFunc {
	return func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) error {
			// Phase 0: preserve behavior; full port later.
			return next(c)
		}
	}
}
