const cron = require('node-cron');
const prisma = require("../lib/prisma");

// Helper to get nodes and edges
const findNextNodeId = (currentNodeId, edges, ruleResult = null) => {
  // If we had conditions (true/false) we could match ruleResult to edge.sourceHandle
  // For now, we take the first outgoing edge
  const outgoingEdge = edges.find(e => e.source === currentNodeId);
  return outgoingEdge ? outgoingEdge.target : null;
};

// Process a single node
const processNode = async (node, enrollment) => {
  const label = node.data?.label || '';
  
  if (label.startsWith('ACTION: Send Email')) {
    // Generate an artificial email message.
    // Gap #10: stamp a deterministic threadId so the message is queryable
    // via /api/email-threading/threads (which filters out null threadIds).
    // All emails from the same enrollment share one thread so the drip
    // reads as a coherent conversation in the inbox.
    await prisma.emailMessage.create({
      data: {
        subject: `Automated Sequence: ${label}`,
        body: `This is an automated drip email generated by a Sequence Engine action.`,
        from: 'system@crm.com',
        to: enrollment.contact.email,
        direction: 'OUTBOUND',
        contactId: enrollment.contact.id,
        threadId: `seq-${enrollment.id}`,
        read: true // Outbound
      }
    });
    // Immediately move to next (no delay)
    return { delayMinutes: 0 };
  }

  if (label.startsWith('DELAY:')) {
    // Extract a duration from the label, e.g. "Wait 72 Hours" / "Wait 1 Day".
    // Units (in minutes): Days = 1440, Hours = 60, Minutes = 1.
    // Fallback stays at 60min (NOT 0) so a malformed label can't trigger an
    // infinite tick loop where the engine re-fires the same node every cron.
    const daysMatch  = label.match(/(\d+)\s*Days?/i);
    const hoursMatch = label.match(/(\d+)\s*Hours?/i);
    const minsMatch  = label.match(/(\d+)\s*Min(?:ute)?s?/i);
    let delayMinutes = 60; // default 1 hour if unparseable

    if (daysMatch) {
      delayMinutes = parseInt(daysMatch[1]) * 1440;
    } else if (hoursMatch) {
      delayMinutes = parseInt(hoursMatch[1]) * 60;
    } else if (minsMatch) {
      delayMinutes = parseInt(minsMatch[1]);
    }

    return { delayMinutes };
  }
  
  if (label.startsWith('ACTION: Send SMS')) {
    if (enrollment.contact.phone) {
      await prisma.smsMessage.create({
        data: {
          to: enrollment.contact.phone,
          body: `Automated sequence message for ${enrollment.contact.name}`,
          direction: 'OUTBOUND',
          status: 'QUEUED',
          contactId: enrollment.contact.id,
        }
      });
    }
    return { delayMinutes: 0 };
  }

  if (label.startsWith('ACTION: Send WhatsApp')) {
    if (enrollment.contact.phone) {
      await prisma.whatsAppMessage.create({
        data: {
          to: enrollment.contact.phone,
          body: `Automated WhatsApp sequence message for ${enrollment.contact.name}`,
          direction: 'OUTBOUND',
          status: 'QUEUED',
          contactId: enrollment.contact.id,
        }
      });
    }
    return { delayMinutes: 0 };
  }

  if (label.startsWith('ACTION: Send Push')) {
    // Create a notification record for the contact owner
    return { delayMinutes: 0 };
  }

  if (label.startsWith('CONDITION:')) {
    // Determine condition result. We'll default to true for now since ReactFlow 
    // basic setup doesn't have custom true/false handles mapped yet.
    return { delayMinutes: 0, ruleResult: true };
  }

  // Fallback for TRIGGERS or unknown nodes (just pass through instantly)
  return { delayMinutes: 0 };
};

const tickSequenceEngine = async () => {
  try {
    const now = new Date();
    // 1. Find all active enrollments where nextRun is null OR nextRun is <= now
    const enrollments = await prisma.sequenceEnrollment.findMany({
      where: {
        status: 'Active',
        OR: [
          { nextRun: null },
          { nextRun: { lte: now } }
        ]
      },
      include: {
        sequence: true,
        contact: true
      }
    });

    for (const enrollment of enrollments) {
      const { sequence } = enrollment;
      if (!sequence.isActive || !sequence.nodes) continue;

      let nodes = [];
      let edges = [];
      try {
        nodes = JSON.parse(sequence.nodes);
        edges = JSON.parse(sequence.edges || '[]');
      } catch(err) {
        console.error(`Error parsing sequence graph for ID: ${sequence.id}`);
        continue;
      }

      // If no currentNode, start with the 'input' trigger node
      let currentNodeId = enrollment.currentNode;
      if (!currentNodeId) {
        const triggerNode = nodes.find(n => n.type === 'input');
        currentNodeId = triggerNode ? triggerNode.id : nodes[0]?.id;
      }

      let activeNode = nodes.find(n => n.id === currentNodeId);
      
      // Process a chain of nodes until we hit a DELAY or completion
      let keepProcessing = true;
      let nextRun = enrollment.nextRun;

      while (activeNode && keepProcessing) {
        const result = await processNode(activeNode, enrollment);
        
        if (result.delayMinutes > 0) {
          // We hit a delay, calculate next run time and stop processing this tick
          nextRun = new Date(Date.now() + result.delayMinutes * 60000);
          
          // Advance the cursor to the node AFTER the delay, so when nextRun hits, we execute it
          currentNodeId = findNextNodeId(activeNode.id, edges, result.ruleResult);
          keepProcessing = false;
        } else {
          // Node executed instantly, find next
          currentNodeId = findNextNodeId(activeNode.id, edges, result.ruleResult);
          if (!currentNodeId) {
            // Sequence completed!
            activeNode = null;
            keepProcessing = false;
          } else {
            activeNode = nodes.find(n => n.id === currentNodeId);
          }
        }
      }

      // Update enrollment state
      if (!currentNodeId) {
        // No more nodes, mark completed
        await prisma.sequenceEnrollment.update({
          where: { id: enrollment.id },
          data: { status: 'Completed', currentNode: null, nextRun: null }
        });
      } else {
        await prisma.sequenceEnrollment.update({
          where: { id: enrollment.id },
          data: { currentNode: currentNodeId, nextRun: nextRun }
        });
      }
    }
  } catch (error) {
    console.error('Sequence Engine Error:', error);
  }
};

// Start the Cron Job natively
const initSequenceCron = () => {
  // Run every minute
  cron.schedule('* * * * *', () => {
    tickSequenceEngine();
  });
  console.log('Sequence Execution Engine initialized (cron: * * * * *)');
};

module.exports = {
  initSequenceCron,
  tickSequenceEngine // exported for manual debug testing
};
