/**
 * guardTeeContent.js — PR-E Phase 2.4.0 safety layer.
 *
 * Semantic-payload-aware guard for the TEE generation path. Sits
 * BETWEEN the LLM and `teeContentBridge` so banned content never
 * reaches the bridge (and thus never reaches `LandingPage.content` or
 * the renderer).
 *
 * Architectural placement
 * ───────────────────────
 *   LLM (semantic JSON output)
 *      ↓
 *   guardTeeContent()                ← this module
 *      ↓
 *   teeContentBridge.mapTeeOutputToContent()
 *      ↓
 *   destinationImageProvider.applyImagesToContent()
 *      ↓
 *   LandingPage.content
 *
 * The legacy `lib/landingPageGuard.js` validates the BLOCK-ARRAY shape
 * (rawOutput.blocks[]) — it does not know how to walk a semantic
 * template payload. This module is the parallel guard for the TEE
 * path; the two run in different generation flows.
 *
 * Hard contract
 * ─────────────
 *   1. NO pricing claims generated by AI
 *        - currency symbols (₹, $, €, £, ¥)
 *        - currency words ("INR", "USD", "EUR", "GBP", "JPY", "AED", "SGD")
 *        - large numerals attached to currency cues ("lakh", "crore", "thousand")
 *        - discount phrasing ("save X%", "X% off", "limited time", "ends today")
 *        Investment tier amounts MUST remain null — bridge already
 *        enforces this; the guard double-checks at the boundary.
 *
 *   2. NO testimonials — `testimonials.items` must be empty.
 *
 *   3. NO ratings — "5/5", "4.8/5", "5★", "5 stars" patterns banned.
 *
 *   4. NO fake urgency claims — "limited time", "only X left", "act now",
 *      "ends today", "hurry", "last chance", "exclusive offer". The
 *      countdown timer is rendered from a REAL deadline the operator
 *      sets; the AI never invents urgency.
 *
 *   5. NO unsupported URLs — any URL must be either:
 *        - a relative path (/p/<slug>, /uploads/, /api/...)
 *        - https://images.unsplash.com / pexels.com / pixabay.com
 *        - https:// to a configurable provider allowlist
 *      Anything else (javascript:, data:, vbscript:, file://, arbitrary
 *      http://, suspicious-looking host) is stripped.
 *
 *   6. Required semantic slots present — minimal contract enforced
 *      (mirrors `CRITICAL_SLOTS` in `teeContentBridge` but at the
 *      semantic-payload edge — bridge's check is a secondary safety
 *      net, this is the primary).
 *
 *   7. Valid template payload shape — the LLM must emit an object
 *      (not array, not null, not a string). Top-level keys that fall
 *      outside the known slot set are silently dropped.
 *
 * Public surface
 * ──────────────
 *   guardTeeContent(rawLLMOutput, { family, traits, input }) →
 *     {
 *       accepted:  boolean,
 *       verdict:   'clean' | 'scrubbed' | 'fallback',
 *       output:    object  // the sanitized semantic payload
 *       issues:    string[] // catalogue of what got stripped (for audit)
 *     }
 *
 *   isPricingText(string)
 *   isRatingText(string)
 *   isUrgencyText(string)
 *   isSafeUrl(string)
 *   stripBannedTextFields(payload, issues)
 *
 * Never throws — always returns the shape above so the orchestrator
 * can continue + log issues. Failure to validate at this layer is
 * treated as "scrub + log", never "halt the pipeline" — the
 * operator's ability to see [REVIEW] markers and fix manually is the
 * recovery path.
 */

'use strict';

// ── Known top-level slot keys the LLM may populate ──────────────────
// Anything outside this set is dropped silently (drops cover prompt
// leakage like {{prompt_template}}, weird LLM hallucinations).
const KNOWN_SLOTS = Object.freeze(new Set([
  'brand', 'nav', 'hero', 'marquee', 'preview', 'programme', 'cultural',
  'safety', 'testimonials', 'investment', 'registration', 'brochure',
  'faq', 'details', 'finalCta', 'contact', 'floatingCta',
  // TEE-only metadata; not LLM-emitted but tolerated if present.
  '_tee', '_locked', '_sectionOrder', '_imageStrategy', '_teeOverrides',
]));

// ── Banned text patterns ────────────────────────────────────────────

// Currency symbols + currency-word patterns. The investment-tier
// guard separately forces null amount/tag/date/vendor.
const PRICING_PATTERNS = [
  /[₹$€£¥]/,                                  // ₹ $ € £ ¥
  /\b(USD|EUR|GBP|INR|JPY|AED|SGD|CAD|AUD|NZD|CHF)\b/i,
  /\b\d+\s*(lakh|crore|thousand|k|hundred)\b/i,
  /\b\d+\s*%\s*(off|discount|savings?|cashback)/i,
  /\bsave\s+(\d+|up\s+to)\b/i,
  /\b(rs\.?|rs\s)\s*\d+/i,
  /\bpriced?\s+(at|from)\s+\d+/i,
  /\bonly\s+\d+\s+(rupees|dollars|euros|pounds)/i,
];

// Rating / star phrases ("5/5", "4.8/5", "5 stars", "5★", "★★★★★").
const RATING_PATTERNS = [
  /\b[1-5](?:\.[0-9]+)?\s*\/\s*5\b/,               // 5/5, 4.8/5
  /\b[1-5](?:\.[0-9]+)?\s*★/,                       // 5★, 4.8★
  /★★★★★/,                                          // five literal stars
  /\b[1-5]\s*-?\s*star\b/i,                        // 5-star, 5 star
  /\b(rated|rating)\s+[1-5](?:\.[0-9]+)?\b/i,
  /\b(top|best|highest)\s*[-]?\s*rated\b/i,        // top-rated, top rated, highest-rated
  /\baward[-\s]+winning\b/i,                        // award-winning, award winning
];

// Fake-urgency phrases (real countdowns are rendered from an operator-
// set deadline; these are AI-fabricated urgency).
const URGENCY_PATTERNS = [
  /\bact\s+now\b/i,
  /\b(hurry|don'?t\s+miss|last\s+chance|final\s+call)\b/i,
  /\b(limited[-\s]time|exclusive\s+offer|while\s+stocks?\s+last)\b/i,
  /\bonly\s+\d+\s+(spots?|seats?|left|remaining)\s+(left|remaining|available)/i,
  /\bends?\s+(today|tomorrow|tonight|this\s+(week|weekend))\b/i,
  /\b(book|register|reserve)\s+(now|today)\s+(or\s+miss\s+out|to\s+secure|to\s+lock)/i,
];

// Sub-set of pricing that ONLY scrubs in copy slots (not in investment
// where currency is a controlled slot). Currency symbol on its own is
// fine in `investment.currency` — banned in narrative text fields.

// Promo / discount language — banned even without a number attached.
const PROMO_PATTERNS = [
  /\bdiscount(s|ed)?\b/i,
  /\bpromo\s*code\b/i,
  /\bcoupon\b/i,
  /\bcashback\b/i,
  /\bfree\s+(gift|bonus|trial|month)/i,
  /\bguaranteed\s+(refund|lowest|best|cheapest)/i,
];

// ── URL safety ─────────────────────────────────────────────────────

const SAFE_URL_HOSTS = Object.freeze([
  'images.unsplash.com',
  'unsplash.com',
  'images.pexels.com',
  'pexels.com',
  'pixabay.com',
  'cdn.pixabay.com',
]);

const UNSAFE_URL_SCHEMES = Object.freeze([
  'javascript:', 'data:', 'vbscript:', 'file:', 'ftp:', 'about:',
  'chrome:', 'chrome-extension:', 'jar:', 'view-source:',
]);

// ── Required slot specs (mirror teeContentBridge CRITICAL_SLOTS) ───

const REQUIRED_SLOT_SPECS = Object.freeze({
  educational: [
    { path: 'brand.label', kind: 'string' },
    { path: 'brand.programmeName', kind: 'string' },
    { path: 'hero.headline', kind: 'string' },
    { path: 'hero.lede', kind: 'string' },
    { path: 'cultural.items', kind: 'array', min: 2 },
    { path: 'safety.features', kind: 'array', min: 2 },
    { path: 'faq.items', kind: 'array', min: 3 },
    { path: 'contact.label', kind: 'string' },
  ],
  religious: [
    { path: 'brand.label', kind: 'string' },
    { path: 'brand.programmeName', kind: 'string' },
    { path: 'hero.headline', kind: 'string' },
    { path: 'hero.lede', kind: 'string' },
    { path: 'programme.leftHeadline', kind: 'string' },
    { path: 'cultural.items', kind: 'array', min: 2 },
    { path: 'safety.features', kind: 'array', min: 2 },
    { path: 'faq.items', kind: 'array', min: 3 },
    { path: 'contact.label', kind: 'string' },
  ],
  family: [
    { path: 'brand.label', kind: 'string' },
    { path: 'brand.programmeName', kind: 'string' },
    { path: 'hero.headline', kind: 'string' },
    { path: 'hero.lede', kind: 'string' },
    { path: 'cultural.items', kind: 'array', min: 2 },
    { path: 'safety.features', kind: 'array', min: 2 },
    { path: 'faq.items', kind: 'array', min: 3 },
    { path: 'contact.label', kind: 'string' },
  ],
  luxury: [
    { path: 'brand.label', kind: 'string' },
    { path: 'brand.programmeName', kind: 'string' },
    { path: 'hero.headline', kind: 'string' },
    { path: 'hero.lede', kind: 'string' },
    { path: 'cultural.items', kind: 'array', min: 2 },
    { path: 'investment.tiers', kind: 'array', min: 2 },
    { path: 'faq.items', kind: 'array', min: 3 },
  ],
});

// ── Helpers ─────────────────────────────────────────────────────────

function isObj(v) { return v != null && typeof v === 'object' && !Array.isArray(v); }
function isStr(v) { return typeof v === 'string' && v.length > 0; }
function clone(v) { return v == null ? v : JSON.parse(JSON.stringify(v)); }

function getPath(obj, path) {
  if (!isObj(obj)) return undefined;
  const m = path.match(/^([^.]+)\.(.+)$/);
  if (!m) return obj[path];
  return getPath(obj[m[1]], m[2]);
}

// Determine whether a string contains a banned pricing pattern.
function isPricingText(text) {
  if (!isStr(text)) return false;
  for (const re of PRICING_PATTERNS) { if (re.test(text)) return true; }
  for (const re of PROMO_PATTERNS) { if (re.test(text)) return true; }
  return false;
}

function isRatingText(text) {
  if (!isStr(text)) return false;
  for (const re of RATING_PATTERNS) { if (re.test(text)) return true; }
  return false;
}

function isUrgencyText(text) {
  if (!isStr(text)) return false;
  for (const re of URGENCY_PATTERNS) { if (re.test(text)) return true; }
  return false;
}

function isSafeUrl(url) {
  if (typeof url !== 'string' || url.length === 0) return true;
  const trimmed = url.trim().toLowerCase();
  // Relative paths are always safe.
  if (trimmed.startsWith('/') || trimmed.startsWith('#')) return true;
  // Block dangerous schemes.
  for (const bad of UNSAFE_URL_SCHEMES) {
    if (trimmed.startsWith(bad)) return false;
  }
  // Allow https:// only.
  if (!trimmed.startsWith('https://')) return false;
  // Host check — extract host from URL.
  try {
    const u = new URL(url);
    if (SAFE_URL_HOSTS.includes(u.hostname.toLowerCase())) return true;
  } catch (_e) {
    return false;
  }
  // Anything not in the allowlist: scrub.
  return false;
}

// Recursively walk a value and strip banned text from string fields.
// Mutates a CLONE; the caller passes a deep copy. Logs every strip to
// `issues` for the audit trail.
//
// Array elements that are themselves strings (e.g.
// `cultural.items[0].body[0]` where body is an array of paragraphs)
// also get the banned-text treatment so AI can't smuggle pricing
// claims via array entries.
function stripBannedTextFields(payload, issues = [], path = '') {
  if (Array.isArray(payload)) {
    payload.forEach((item, i) => {
      const subPath = `${path}[${i}]`;
      if (typeof item === 'string') {
        if (isPricingText(item)) {
          issues.push(`pricing-text:${subPath}`);
          payload[i] = '';
        } else if (isRatingText(item)) {
          issues.push(`rating-text:${subPath}`);
          payload[i] = '';
        } else if (isUrgencyText(item)) {
          issues.push(`urgency-text:${subPath}`);
          payload[i] = '';
        }
      } else {
        stripBannedTextFields(item, issues, subPath);
      }
    });
    return payload;
  }
  if (!isObj(payload)) return payload;
  for (const key of Object.keys(payload)) {
    const val = payload[key];
    const subPath = path ? `${path}.${key}` : key;
    if (typeof val === 'string') {
      if (isPricingText(val)) {
        issues.push(`pricing-text:${subPath}`);
        payload[key] = '';
      } else if (isRatingText(val)) {
        issues.push(`rating-text:${subPath}`);
        payload[key] = '';
      } else if (isUrgencyText(val)) {
        issues.push(`urgency-text:${subPath}`);
        payload[key] = '';
      } else if (looksLikeUrlField(key) && !isSafeUrl(val)) {
        issues.push(`unsafe-url:${subPath}`);
        payload[key] = '';
      }
    } else if (isObj(val) || Array.isArray(val)) {
      stripBannedTextFields(val, issues, subPath);
    }
  }
  return payload;
}

// URL-shaped field names. We scrub these specifically because text
// content fields might legitimately mention "https://example.com" in
// passing — but a slot named `src`, `href`, `url`, `posterUrl`, `img`,
// `image`, etc. IS a URL field and gets the strict allowlist treatment.
function looksLikeUrlField(key) {
  if (typeof key !== 'string') return false;
  const k = key.toLowerCase();
  if (k === 'src' || k === 'href' || k === 'url' || k === 'img' || k === 'image') return true;
  return k.endsWith('url') || k.endsWith('href') || k.endsWith('src')
      || k.endsWith('img') || k.endsWith('image');
}

// Force-clear slots that are operator-only regardless of LLM output.
function forceClearOperatorOnlySlots(payload, issues) {
  // 1. Testimonials always empty.
  if (payload.testimonials && Array.isArray(payload.testimonials.items) && payload.testimonials.items.length > 0) {
    issues.push('testimonials-emptied');
    payload.testimonials.items = [];
  }
  // 2. Investment tier commercial fields → null.
  if (payload.investment && Array.isArray(payload.investment.tiers)) {
    let strippedAny = false;
    payload.investment.tiers = payload.investment.tiers.map((t) => {
      const tNew = { ...t };
      ['amount', 'tag', 'date', 'vendor'].forEach((field) => {
        if (tNew[field] != null && tNew[field] !== '') {
          strippedAny = true;
          tNew[field] = null;
        }
      });
      return tNew;
    });
    if (strippedAny) issues.push('investment-tier-amounts-nulled');
  }
  // 3. Image URLs forced empty (image provider populates them).
  if (payload.hero) {
    if (payload.hero.posterUrl) {
      issues.push('hero-posterUrl-cleared');
      payload.hero.posterUrl = '';
    }
  }
  if (payload.brand) {
    if (payload.brand.logoUrl) {
      issues.push('brand-logoUrl-cleared');
      payload.brand.logoUrl = '';
    }
    if (Array.isArray(payload.brand.partnerLogos) && payload.brand.partnerLogos.length > 0) {
      issues.push('brand-partnerLogos-cleared');
      payload.brand.partnerLogos = [];
    }
  }
  if (payload.marquee && Array.isArray(payload.marquee.cities)) {
    payload.marquee.cities = payload.marquee.cities.map((c) => {
      const cNew = { ...c };
      if (cNew.img) { issues.push('marquee-city-img-cleared'); cNew.img = null; }
      return cNew;
    });
  }
  // 4. Operator phone/email lines — slot stays but inner data clears.
  if (payload.contact && Array.isArray(payload.contact.sections)) {
    let clearedAny = false;
    payload.contact.sections = payload.contact.sections.map((s) => {
      if (!isObj(s)) return s;
      if (Array.isArray(s.lines) && s.lines.length > 0) {
        // Look for email/phone leakage and scrub.
        const cleanLines = s.lines.filter((line) => {
          if (!isStr(line)) return false;
          if (/\b[\w.+-]+@[\w-]+\.[\w.-]+\b/.test(line)) { clearedAny = true; return false; }
          if (/(\+\d[\d\s-]{7,}|\(\d{3}\)\s?\d{3}[-\s]?\d{4})/.test(line)) { clearedAny = true; return false; }
          return true;
        });
        return { ...s, lines: cleanLines };
      }
      return s;
    });
    if (clearedAny) issues.push('contact-sections-scrubbed');
  }
  return payload;
}

// Drop unknown top-level keys. This is a defensive measure against
// prompt-leakage or hallucinated slots.
function dropUnknownTopLevelKeys(payload, issues) {
  for (const key of Object.keys(payload)) {
    if (!KNOWN_SLOTS.has(key)) {
      issues.push(`unknown-slot:${key}`);
      delete payload[key];
    }
  }
  return payload;
}

// Required-slot validation. Returns the missing-spec list. Does NOT
// throw — the orchestrator decides fallback policy.
function checkRequiredSlots(payload, family) {
  const specs = REQUIRED_SLOT_SPECS[family] || REQUIRED_SLOT_SPECS.educational;
  const missing = [];
  for (const spec of specs) {
    const v = getPath(payload, spec.path);
    if (spec.kind === 'string') {
      if (!isStr(v)) missing.push(spec.path);
    } else if (spec.kind === 'array') {
      const len = Array.isArray(v) ? v.length : 0;
      if (len < (spec.min || 1)) missing.push(`${spec.path}[length>=${spec.min || 1}]`);
    }
  }
  return missing;
}

// ── Public — guardTeeContent ─────────────────────────────────────────

function guardTeeContent(rawLLMOutput, { family, traits, input } = {}) {
  // Top-level shape check.
  if (!isObj(rawLLMOutput)) {
    return {
      accepted: false,
      verdict: 'fallback',
      output: {},
      issues: ['payload-not-an-object'],
    };
  }

  const issues = [];
  const out = clone(rawLLMOutput);

  // Step 1 — drop unknown top-level keys.
  dropUnknownTopLevelKeys(out, issues);

  // Step 2 — recursively strip banned text patterns.
  stripBannedTextFields(out, issues);

  // Step 3 — force-clear operator-only slots.
  forceClearOperatorOnlySlots(out, issues);

  // Step 4 — required-slot validation. We return verdict based on
  // outcome but don't throw — the bridge has its own safety net.
  const missing = checkRequiredSlots(out, family || 'educational');
  if (missing.length > 0) {
    missing.forEach((m) => issues.push(`missing-required:${m}`));
  }

  let verdict = 'clean';
  if (issues.length > 0 && missing.length === 0) verdict = 'scrubbed';
  if (missing.length > 0) verdict = 'fallback';

  return {
    accepted: missing.length === 0,
    verdict,
    output: out,
    issues,
  };
}

module.exports = {
  guardTeeContent,
  // Public helpers (used by tests + integrations)
  isPricingText,
  isRatingText,
  isUrgencyText,
  isSafeUrl,
  stripBannedTextFields,
  forceClearOperatorOnlySlots,
  dropUnknownTopLevelKeys,
  checkRequiredSlots,
  // Constants for inspection
  KNOWN_SLOTS,
  SAFE_URL_HOSTS,
  REQUIRED_SLOT_SPECS,
  PRICING_PATTERNS,
  RATING_PATTERNS,
  URGENCY_PATTERNS,
};
