$ErrorActionPreference = "Stop"
$installDirectory = Split-Path -Parent $MyInvocation.MyCommand.Path
$executable = Join-Path $installDirectory "TallyConnector.exe"
$configuration = Join-Path $installDirectory "config.json"
$launcher = Join-Path $installDirectory "run-hidden.vbs"
$shortcutPath = Join-Path ([Environment]::GetFolderPath("Startup")) "Globussoft Tally Connector.lnk"
$wscript = Join-Path $env:WINDIR "System32\wscript.exe"

foreach ($required in @($executable, $configuration, $launcher, $wscript)) {
  if (-not (Test-Path -LiteralPath $required -PathType Leaf)) {
    throw "Missing required file: $required"
  }
}

$shell = New-Object -ComObject WScript.Shell
$shortcut = $shell.CreateShortcut($shortcutPath)
$shortcut.TargetPath = $wscript
$shortcut.Arguments = '"' + $launcher + '"'
$shortcut.WorkingDirectory = $installDirectory
$shortcut.WindowStyle = 7
$shortcut.Description = "Starts Globussoft Tally Connector hidden at sign-in"
$shortcut.Save()

$running = Get-CimInstance Win32_Process -Filter "Name = 'TallyConnector.exe'" |
  Where-Object { $_.ExecutablePath -and $_.ExecutablePath.Equals($executable, [StringComparison]::OrdinalIgnoreCase) }
if (-not $running) {
  $shell.Run('"' + $wscript + '" "' + $launcher + '"', 0, $false) | Out-Null
}

Write-Host "Globussoft Tally Connector installed in Startup and running from $installDirectory"

# SIG # Begin signature block
# MIISGAYJKoZIhvcNAQcCoIISCTCCEgUCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCDyVnXUhlmime0b
# Lv+VigWPXm1UPBxD2IghX3RflTFD/qCCDkgwggawMIIEmKADAgECAhAIrUCyYNKc
# TJ9ezam9k67ZMA0GCSqGSIb3DQEBDAUAMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQK
# EwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNV
# BAMTGERpZ2lDZXJ0IFRydXN0ZWQgUm9vdCBHNDAeFw0yMTA0MjkwMDAwMDBaFw0z
# NjA0MjgyMzU5NTlaMGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwg
# SW5jLjFBMD8GA1UEAxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBDb2RlIFNpZ25pbmcg
# UlNBNDA5NiBTSEEzODQgMjAyMSBDQTEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAw
# ggIKAoICAQDVtC9C0CiteLdd1TlZG7GIQvUzjOs9gZdwxbvEhSYwn6SOaNhc9es0
# JAfhS0/TeEP0F9ce2vnS1WcaUk8OoVf8iJnBkcyBAz5NcCRks43iCH00fUyAVxJr
# Q5qZ8sU7H/Lvy0daE6ZMswEgJfMQ04uy+wjwiuCdCcBlp/qYgEk1hz1RGeiQIXhF
# LqGfLOEYwhrMxe6TSXBCMo/7xuoc82VokaJNTIIRSFJo3hC9FFdd6BgTZcV/sk+F
# LEikVoQ11vkunKoAFdE3/hoGlMJ8yOobMubKwvSnowMOdKWvObarYBLj6Na59zHh
# 3K3kGKDYwSNHR7OhD26jq22YBoMbt2pnLdK9RBqSEIGPsDsJ18ebMlrC/2pgVItJ
# wZPt4bRc4G/rJvmM1bL5OBDm6s6R9b7T+2+TYTRcvJNFKIM2KmYoX7BzzosmJQay
# g9Rc9hUZTO1i4F4z8ujo7AqnsAMrkbI2eb73rQgedaZlzLvjSFDzd5Ea/ttQokbI
# YViY9XwCFjyDKK05huzUtw1T0PhH5nUwjewwk3YUpltLXXRhTT8SkXbev1jLchAp
# QfDVxW0mdmgRQRNYmtwmKwH0iU1Z23jPgUo+QEdfyYFQc4UQIyFZYIpkVMHMIRro
# OBl8ZhzNeDhFMJlP/2NPTLuqDQhTQXxYPUez+rbsjDIJAsxsPAxWEQIDAQABo4IB
# WTCCAVUwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUaDfg67Y7+F8Rhvv+
# YXsIiGX0TkIwHwYDVR0jBBgwFoAU7NfjgtJxXWRM3y5nP+e6mK4cD08wDgYDVR0P
# AQH/BAQDAgGGMBMGA1UdJQQMMAoGCCsGAQUFBwMDMHcGCCsGAQUFBwEBBGswaTAk
# BggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEEGCCsGAQUFBzAC
# hjVodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkUm9v
# dEc0LmNydDBDBgNVHR8EPDA6MDigNqA0hjJodHRwOi8vY3JsMy5kaWdpY2VydC5j
# b20vRGlnaUNlcnRUcnVzdGVkUm9vdEc0LmNybDAcBgNVHSAEFTATMAcGBWeBDAED
# MAgGBmeBDAEEATANBgkqhkiG9w0BAQwFAAOCAgEAOiNEPY0Idu6PvDqZ01bgAhql
# +Eg08yy25nRm95RysQDKr2wwJxMSnpBEn0v9nqN8JtU3vDpdSG2V1T9J9Ce7FoFF
# UP2cvbaF4HZ+N3HLIvdaqpDP9ZNq4+sg0dVQeYiaiorBtr2hSBh+3NiAGhEZGM1h
# mYFW9snjdufE5BtfQ/g+lP92OT2e1JnPSt0o618moZVYSNUa/tcnP/2Q0XaG3Ryw
# YFzzDaju4ImhvTnhOE7abrs2nfvlIVNaw8rpavGiPttDuDPITzgUkpn13c5Ubdld
# AhQfQDN8A+KVssIhdXNSy0bYxDQcoqVLjc1vdjcshT8azibpGL6QB7BDf5WIIIJw
# 8MzK7/0pNVwfiThV9zeKiwmhywvpMRr/LhlcOXHhvpynCgbWJme3kuZOX956rEnP
# LqR0kq3bPKSchh/jwVYbKyP/j7XqiHtwa+aguv06P0WmxOgWkVKLQcBIhEuWTatE
# QOON8BUozu3xGFYHKi8QxAwIZDwzj64ojDzLj4gLDb879M4ee47vtevLt/B3E+bn
# KD+sEq6lLyJsQfmCXBVmzGwOysWGw/YmMwwHS6DTBwJqakAwSEs0qFEgu60bhQji
# WQ1tygVQK+pKHJ6l/aCnHwZ05/LWUpD9r4VIIflXO7ScA+2GRfS0YW6/aOImYIbq
# yK+p/pQd52MbOoZWeE4wggeQMIIFeKADAgECAhAF+WgSLEZQTAMRQh2/LTAqMA0G
# CSqGSIb3DQEBCwUAMGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwg
# SW5jLjFBMD8GA1UEAxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBDb2RlIFNpZ25pbmcg
# UlNBNDA5NiBTSEEzODQgMjAyMSBDQTEwHhcNMjUxMTEzMDAwMDAwWhcNMjYxMTI4
# MjM1OTU5WjCBlzELMAkGA1UEBhMCSU4xFTATBgNVBAgTDENoaGF0dGlzZ2FyaDEN
# MAsGA1UEBxMERHVyZzEwMC4GA1UEChMnR2xvYnVzc29mdCBUZWNobm9sb2dpZXMg
# UHJpdmF0ZSBMaW1pdGVkMTAwLgYDVQQDEydHbG9idXNzb2Z0IFRlY2hub2xvZ2ll
# cyBQcml2YXRlIExpbWl0ZWQwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
# AQCuINJSqATEAjWbmUROP3Rj7pQFJV8OqphcGc82Icjts5UGrM4wQQ3sHXvqdcTC
# 6xosu9fuCwNVOOVh1W5ztZYpW2hDnwgUF80+jGzyVpPNyhhPw2FppDiIYLEq3HjB
# hC+X1+Jkzf8Vkh2YT9lVKlfx1UMpKmggDh03kpOiKJh46xgKlTyVrzie5qxZKfqD
# ZUjVbLLDFzCB4JJcanRggAj3BjmmslfikMp9qTDQe7YYw2O2yifHRipPL0Z9nKn3
# Ur3Z7Qwh+r5eNqoMXa2OxIFG1Fbwy7Htko8IT0DGZDsD4QlY8j8DlrInRSkw7H0h
# dMGQskL+7RcOxecODuKO5UuYxFA/iMBDgmBiEFJIDikMnh41vXuu5T8kw+BpBYlu
# fHktVtyeKI0VKtVsJRzwM+GHT/OFi0mRFAs4XyfF3IRs5iD38cxUIJmgqoPFeCKR
# iHV61dCsv573Cj5a1OtljM9YiOw6C3fLuYNYK/grJ5vnVZPasSXDCVQs4/Y1RdrX
# yXSDU1D/jMaAJNCXCq9AWnah7JsktjVzIrXhwbyvbYWIBlENzJrDn/xDtMNhR3jP
# k7Uss6ODZbsKAFNmqRM2SY3O8IAJjPOI9b/Qn4Sm+PxlfUe3JqT5MGiuzEoaDGth
# v9k52FU41oiQiXSWbsrGiwN6q5896NZqhQXfGzhhCh3+4QIDAQABo4ICAzCCAf8w
# HwYDVR0jBBgwFoAUaDfg67Y7+F8Rhvv+YXsIiGX0TkIwHQYDVR0OBBYEFMu86UE9
# au4jnIynkHMEVb0wDrfQMD4GA1UdIAQ3MDUwMwYGZ4EMAQQBMCkwJwYIKwYBBQUH
# AgEWG2h0dHA6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAOBgNVHQ8BAf8EBAMCB4Aw
# EwYDVR0lBAwwCgYIKwYBBQUHAwMwgbUGA1UdHwSBrTCBqjBToFGgT4ZNaHR0cDov
# L2NybDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZEc0Q29kZVNpZ25pbmdS
# U0E0MDk2U0hBMzg0MjAyMUNBMS5jcmwwU6BRoE+GTWh0dHA6Ly9jcmw0LmRpZ2lj
# ZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRHNENvZGVTaWduaW5nUlNBNDA5NlNIQTM4
# NDIwMjFDQTEuY3JsMIGUBggrBgEFBQcBAQSBhzCBhDAkBggrBgEFBQcwAYYYaHR0
# cDovL29jc3AuZGlnaWNlcnQuY29tMFwGCCsGAQUFBzAChlBodHRwOi8vY2FjZXJ0
# cy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkRzRDb2RlU2lnbmluZ1JTQTQw
# OTZTSEEzODQyMDIxQ0ExLmNydDAJBgNVHRMEAjAAMA0GCSqGSIb3DQEBCwUAA4IC
# AQBfN7aLrDd+JxCSA9eATMponJGz7/LkVTVvnNgM/hFJlJm9Qxfpj72uzjnlm7NE
# 0qR+U7f8KpaKtq+RG0jAj3jedJbYmvmOWeowCum/55zT9FCqgJ9j1r+Isfj4v9Nq
# Yzcok1qlkuGqdBi30tFVxpSO7o60SGs6r61yjx5zrOTVDweJE84hh5O25PMYCsbU
# J/KEp/qttGVvsROOVdglEft6YKW0RMsoDC4W7hav+8ILNCAX6f80xgIareJHSeY/
# rfaJaEuPNhCll6QJenLV7oWmsxMUxGS2HwfABUrT6RQ8mkdah28gMkGjxlzkhFiC
# 4XFmXqDiJ4KvcyuNWzrWY1fNqh043QuCMJvffLNUrXjRZxftSDWY61CIu7YCfkye
# Vub1qLRLTlx6cgSfdJzviuIGZyyZuDBYE2+p69PG8/vqGmLejR/vSTvsd27y50TY
# hlOkyqxMqR2Kgl/TQvmSFbGfO9mq3c4ePAUriBw29KDXkZGsP/56r9kFU568TNkd
# U7KKLJ0oPuoiDuCB6F/mTz4w++WWRY8kOydjNRY75rpBAP6r/qTHKY2KETWyRe8T
# 7HhNw6IYJQdtvjKjqdFTxwSqC5Jmy8amkPQzHnLUXeWadcmqmZSUE1vxfI9TMAv/
# ueMg2XnNCcS2nEkqcHrKgQrlX3OzSI9ewW45vYRx0mFEqjGCAyYwggMiAgEBMH0w
# aTELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJbmMuMUEwPwYDVQQD
# EzhEaWdpQ2VydCBUcnVzdGVkIEc0IENvZGUgU2lnbmluZyBSU0E0MDk2IFNIQTM4
# NCAyMDIxIENBMQIQBfloEixGUEwDEUIdvy0wKjANBglghkgBZQMEAgEFAKB8MBAG
# CisGAQQBgjcCAQwxAjAAMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
# AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3DQEJBDEiBCB660TzHNdv
# Yx9DY+tYRTtqctnt8eTmNHIalfLoern88jANBgkqhkiG9w0BAQEFAASCAgAEFdSg
# XHeVvaKUGbEjANOqbSnqiZJbp/+hyUx4Ao09ezVTP9j53gO7jYm2R/Be+6Aslroc
# Shaysu6hslDzVRF6V7aAt2S8yuLzGOu7LstfozKIrf6fAmAS7EcHJ6E2sqTjK+0G
# sBeN6+kbWMXzjKZ6nm9Ly+chxQK8Z7qmbUY3cYe2FdF38xsozXKcVsr0PVl3Vt2A
# juZCuE5eJLelOK6yhMfhJb3rRy+g6v3oWC2f46/5XvnUDcYFYq3vObO66YYpTLEv
# MnvCjL5JHREZtR+6JewUZLlye9VS9M1YENbPcYj204PArlr8bKD76BqT6Uatz/y8
# IGe5H7Ief9L29jGvRyzV56fy9eZExZ2BJZ7KD/UsDrGE4y2wYCyr12+IXIn80w3A
# Rdu7yhmfzWZ5m3UnJrSLQCjz+uzZD0g3fbU2rqdM9gbLRxienh/uQpRq6sRDg04t
# R8OwVCwgY5gYKgXFlBR3aju4oFADKIzgLE2sRPlbyrnAZHWK2DQO+bju+6xAYV2S
# 97V7NwdWDvra4yoLeJv2xf9e2ZJUTOUH3FG9jPzbpxPyLGIba7sF7M5cF/yLiCP4
# FYrDPpH1wZ04Zy8o1kdUbohMghfdvZSAGS01TQ4V9Fe4d6yIh8TCNBHQ3znh/5PZ
# BSLI4r/juStDDuY8VSJr1Bno4M6tX8ij1qEdVg==
# SIG # End signature block
